/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiVerifyDataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiVerifyDataRequest{}

// ApiVerifyDataRequest struct for ApiVerifyDataRequest
type ApiVerifyDataRequest struct {
	Key       string `json:"key"`
	Payload   string `json:"payload"`
	Signature string `json:"signature"`
}

type _ApiVerifyDataRequest ApiVerifyDataRequest

// NewApiVerifyDataRequest instantiates a new ApiVerifyDataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiVerifyDataRequest(key string, payload string, signature string) *ApiVerifyDataRequest {
	this := ApiVerifyDataRequest{}
	this.Key = key
	this.Payload = payload
	this.Signature = signature
	return &this
}

// NewApiVerifyDataRequestWithDefaults instantiates a new ApiVerifyDataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiVerifyDataRequestWithDefaults() *ApiVerifyDataRequest {
	this := ApiVerifyDataRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *ApiVerifyDataRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ApiVerifyDataRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ApiVerifyDataRequest) SetKey(v string) {
	o.Key = v
}

// GetPayload returns the Payload field value
func (o *ApiVerifyDataRequest) GetPayload() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *ApiVerifyDataRequest) GetPayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *ApiVerifyDataRequest) SetPayload(v string) {
	o.Payload = v
}

// GetSignature returns the Signature field value
func (o *ApiVerifyDataRequest) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *ApiVerifyDataRequest) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *ApiVerifyDataRequest) SetSignature(v string) {
	o.Signature = v
}

func (o ApiVerifyDataRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiVerifyDataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["payload"] = o.Payload
	toSerialize["signature"] = o.Signature
	return toSerialize, nil
}

func (o *ApiVerifyDataRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"payload",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiVerifyDataRequest := _ApiVerifyDataRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiVerifyDataRequest)

	if err != nil {
		return err
	}

	*o = ApiVerifyDataRequest(varApiVerifyDataRequest)

	return err
}

type NullableApiVerifyDataRequest struct {
	value *ApiVerifyDataRequest
	isSet bool
}

func (v NullableApiVerifyDataRequest) Get() *ApiVerifyDataRequest {
	return v.value
}

func (v *NullableApiVerifyDataRequest) Set(val *ApiVerifyDataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiVerifyDataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiVerifyDataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiVerifyDataRequest(val *ApiVerifyDataRequest) *NullableApiVerifyDataRequest {
	return &NullableApiVerifyDataRequest{value: val, isSet: true}
}

func (v NullableApiVerifyDataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiVerifyDataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
