/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiScriptValidateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiScriptValidateResponse{}

// ApiScriptValidateResponse struct for ApiScriptValidateResponse
type ApiScriptValidateResponse struct {
	ScriptHash *string `json:"scriptHash,omitempty"`
	Signatures *int32  `json:"signatures,omitempty"`
	Slot       *int64  `json:"slot,omitempty"`
	Valid      *bool   `json:"valid,omitempty"`
}

// NewApiScriptValidateResponse instantiates a new ApiScriptValidateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiScriptValidateResponse() *ApiScriptValidateResponse {
	this := ApiScriptValidateResponse{}
	return &this
}

// NewApiScriptValidateResponseWithDefaults instantiates a new ApiScriptValidateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiScriptValidateResponseWithDefaults() *ApiScriptValidateResponse {
	this := ApiScriptValidateResponse{}
	return &this
}

// GetScriptHash returns the ScriptHash field value if set, zero value otherwise.
func (o *ApiScriptValidateResponse) GetScriptHash() string {
	if o == nil || IsNil(o.ScriptHash) {
		var ret string
		return ret
	}
	return *o.ScriptHash
}

// GetScriptHashOk returns a tuple with the ScriptHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptValidateResponse) GetScriptHashOk() (*string, bool) {
	if o == nil || IsNil(o.ScriptHash) {
		return nil, false
	}
	return o.ScriptHash, true
}

// HasScriptHash returns a boolean if a field has been set.
func (o *ApiScriptValidateResponse) HasScriptHash() bool {
	if o != nil && !IsNil(o.ScriptHash) {
		return true
	}

	return false
}

// SetScriptHash gets a reference to the given string and assigns it to the ScriptHash field.
func (o *ApiScriptValidateResponse) SetScriptHash(v string) {
	o.ScriptHash = &v
}

// GetSignatures returns the Signatures field value if set, zero value otherwise.
func (o *ApiScriptValidateResponse) GetSignatures() int32 {
	if o == nil || IsNil(o.Signatures) {
		var ret int32
		return ret
	}
	return *o.Signatures
}

// GetSignaturesOk returns a tuple with the Signatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptValidateResponse) GetSignaturesOk() (*int32, bool) {
	if o == nil || IsNil(o.Signatures) {
		return nil, false
	}
	return o.Signatures, true
}

// HasSignatures returns a boolean if a field has been set.
func (o *ApiScriptValidateResponse) HasSignatures() bool {
	if o != nil && !IsNil(o.Signatures) {
		return true
	}

	return false
}

// SetSignatures gets a reference to the given int32 and assigns it to the Signatures field.
func (o *ApiScriptValidateResponse) SetSignatures(v int32) {
	o.Signatures = &v
}

// GetSlot returns the Slot field value if set, zero value otherwise.
func (o *ApiScriptValidateResponse) GetSlot() int64 {
	if o == nil || IsNil(o.Slot) {
		var ret int64
		return ret
	}
	return *o.Slot
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptValidateResponse) GetSlotOk() (*int64, bool) {
	if o == nil || IsNil(o.Slot) {
		return nil, false
	}
	return o.Slot, true
}

// HasSlot returns a boolean if a field has been set.
func (o *ApiScriptValidateResponse) HasSlot() bool {
	if o != nil && !IsNil(o.Slot) {
		return true
	}

	return false
}

// SetSlot gets a reference to the given int64 and assigns it to the Slot field.
func (o *ApiScriptValidateResponse) SetSlot(v int64) {
	o.Slot = &v
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *ApiScriptValidateResponse) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptValidateResponse) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *ApiScriptValidateResponse) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *ApiScriptValidateResponse) SetValid(v bool) {
	o.Valid = &v
}

func (o ApiScriptValidateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiScriptValidateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScriptHash) {
		toSerialize["scriptHash"] = o.ScriptHash
	}
	if !IsNil(o.Signatures) {
		toSerialize["signatures"] = o.Signatures
	}
	if !IsNil(o.Slot) {
		toSerialize["slot"] = o.Slot
	}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	return toSerialize, nil
}

type NullableApiScriptValidateResponse struct {
	value *ApiScriptValidateResponse
	isSet bool
}

func (v NullableApiScriptValidateResponse) Get() *ApiScriptValidateResponse {
	return v.value
}

func (v *NullableApiScriptValidateResponse) Set(
	val *ApiScriptValidateResponse,
) {
	v.value = val
	v.isSet = true
}

func (v NullableApiScriptValidateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiScriptValidateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiScriptValidateResponse(
	val *ApiScriptValidateResponse,
) *NullableApiScriptValidateResponse {
	return &NullableApiScriptValidateResponse{value: val, isSet: true}
}

func (v NullableApiScriptValidateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiScriptValidateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
