/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BursaTxInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BursaTxInput{}

// BursaTxInput struct for BursaTxInput
type BursaTxInput struct {
	Index *int32  `json:"index,omitempty"`
	TxId  *string `json:"tx_id,omitempty"`
}

// NewBursaTxInput instantiates a new BursaTxInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBursaTxInput() *BursaTxInput {
	this := BursaTxInput{}
	return &this
}

// NewBursaTxInputWithDefaults instantiates a new BursaTxInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBursaTxInputWithDefaults() *BursaTxInput {
	this := BursaTxInput{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *BursaTxInput) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInput) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *BursaTxInput) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *BursaTxInput) SetIndex(v int32) {
	o.Index = &v
}

// GetTxId returns the TxId field value if set, zero value otherwise.
func (o *BursaTxInput) GetTxId() string {
	if o == nil || IsNil(o.TxId) {
		var ret string
		return ret
	}
	return *o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInput) GetTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TxId) {
		return nil, false
	}
	return o.TxId, true
}

// HasTxId returns a boolean if a field has been set.
func (o *BursaTxInput) HasTxId() bool {
	if o != nil && !IsNil(o.TxId) {
		return true
	}

	return false
}

// SetTxId gets a reference to the given string and assigns it to the TxId field.
func (o *BursaTxInput) SetTxId(v string) {
	o.TxId = &v
}

func (o BursaTxInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BursaTxInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.TxId) {
		toSerialize["tx_id"] = o.TxId
	}
	return toSerialize, nil
}

type NullableBursaTxInput struct {
	value *BursaTxInput
	isSet bool
}

func (v NullableBursaTxInput) Get() *BursaTxInput {
	return v.value
}

func (v *NullableBursaTxInput) Set(val *BursaTxInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBursaTxInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBursaTxInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBursaTxInput(val *BursaTxInput) *NullableBursaTxInput {
	return &NullableBursaTxInput{value: val, isSet: true}
}

func (v NullableBursaTxInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBursaTxInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
