/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCredentialInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCredentialInfo{}

// ApiCredentialInfo struct for ApiCredentialInfo
type ApiCredentialInfo struct {
	// bech32-encoded credential
	Bech32 *string `json:"bech32,omitempty"`
	// hex-encoded credential
	Hex *string `json:"hex,omitempty"`
	// \"key\" or \"script\"
	Type *string `json:"type,omitempty"`
}

// NewApiCredentialInfo instantiates a new ApiCredentialInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCredentialInfo() *ApiCredentialInfo {
	this := ApiCredentialInfo{}
	return &this
}

// NewApiCredentialInfoWithDefaults instantiates a new ApiCredentialInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCredentialInfoWithDefaults() *ApiCredentialInfo {
	this := ApiCredentialInfo{}
	return &this
}

// GetBech32 returns the Bech32 field value if set, zero value otherwise.
func (o *ApiCredentialInfo) GetBech32() string {
	if o == nil || IsNil(o.Bech32) {
		var ret string
		return ret
	}
	return *o.Bech32
}

// GetBech32Ok returns a tuple with the Bech32 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCredentialInfo) GetBech32Ok() (*string, bool) {
	if o == nil || IsNil(o.Bech32) {
		return nil, false
	}
	return o.Bech32, true
}

// HasBech32 returns a boolean if a field has been set.
func (o *ApiCredentialInfo) HasBech32() bool {
	if o != nil && !IsNil(o.Bech32) {
		return true
	}

	return false
}

// SetBech32 gets a reference to the given string and assigns it to the Bech32 field.
func (o *ApiCredentialInfo) SetBech32(v string) {
	o.Bech32 = &v
}

// GetHex returns the Hex field value if set, zero value otherwise.
func (o *ApiCredentialInfo) GetHex() string {
	if o == nil || IsNil(o.Hex) {
		var ret string
		return ret
	}
	return *o.Hex
}

// GetHexOk returns a tuple with the Hex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCredentialInfo) GetHexOk() (*string, bool) {
	if o == nil || IsNil(o.Hex) {
		return nil, false
	}
	return o.Hex, true
}

// HasHex returns a boolean if a field has been set.
func (o *ApiCredentialInfo) HasHex() bool {
	if o != nil && !IsNil(o.Hex) {
		return true
	}

	return false
}

// SetHex gets a reference to the given string and assigns it to the Hex field.
func (o *ApiCredentialInfo) SetHex(v string) {
	o.Hex = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiCredentialInfo) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCredentialInfo) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiCredentialInfo) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiCredentialInfo) SetType(v string) {
	o.Type = &v
}

func (o ApiCredentialInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCredentialInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bech32) {
		toSerialize["bech32"] = o.Bech32
	}
	if !IsNil(o.Hex) {
		toSerialize["hex"] = o.Hex
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiCredentialInfo struct {
	value *ApiCredentialInfo
	isSet bool
}

func (v NullableApiCredentialInfo) Get() *ApiCredentialInfo {
	return v.value
}

func (v *NullableApiCredentialInfo) Set(val *ApiCredentialInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCredentialInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCredentialInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCredentialInfo(val *ApiCredentialInfo) *NullableApiCredentialInfo {
	return &NullableApiCredentialInfo{value: val, isSet: true}
}

func (v NullableApiCredentialInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCredentialInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
