/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BursaTxInspection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BursaTxInspection{}

// BursaTxInspection struct for BursaTxInspection
type BursaTxInspection struct {
	CertificateCount       *int32          `json:"certificate_count,omitempty"`
	Era                    *string         `json:"era,omitempty"`
	Fee                    *string         `json:"fee,omitempty"`
	HasMetadata            *bool           `json:"has_metadata,omitempty"`
	HasMint                *bool           `json:"has_mint,omitempty"`
	HasTreasuryDonation    *bool           `json:"has_treasury_donation,omitempty"`
	Inputs                 []BursaTxInput  `json:"inputs,omitempty"`
	IsValid                *bool           `json:"is_valid,omitempty"`
	NativeScripts          *int32          `json:"native_scripts,omitempty"`
	Outputs                []BursaTxOutput `json:"outputs,omitempty"`
	ProposalProcedureCount *int32          `json:"proposal_procedure_count,omitempty"`
	RequiredSigners        *int32          `json:"required_signers,omitempty"`
	SizeBytes              *int32          `json:"size_bytes,omitempty"`
	Ttl                    *int32          `json:"ttl,omitempty"`
	TxId                   *string         `json:"tx_id,omitempty"`
	ValidityIntervalStart  *int32          `json:"validity_interval_start,omitempty"`
	VkeyWitnesses          *int32          `json:"vkey_witnesses,omitempty"`
	// Conway governance and treasury components. These authorize high-impact actions (casting DRep/committee votes, submitting governance proposals, donating to the treasury) that are independent of outputs/certificates/withdrawals, so the policy engine must inspect and gate them explicitly.
	VotingProcedureCount *int32 `json:"voting_procedure_count,omitempty"`
	WithdrawalCount      *int32 `json:"withdrawal_count,omitempty"`
}

// NewBursaTxInspection instantiates a new BursaTxInspection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBursaTxInspection() *BursaTxInspection {
	this := BursaTxInspection{}
	return &this
}

// NewBursaTxInspectionWithDefaults instantiates a new BursaTxInspection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBursaTxInspectionWithDefaults() *BursaTxInspection {
	this := BursaTxInspection{}
	return &this
}

// GetCertificateCount returns the CertificateCount field value if set, zero value otherwise.
func (o *BursaTxInspection) GetCertificateCount() int32 {
	if o == nil || IsNil(o.CertificateCount) {
		var ret int32
		return ret
	}
	return *o.CertificateCount
}

// GetCertificateCountOk returns a tuple with the CertificateCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetCertificateCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CertificateCount) {
		return nil, false
	}
	return o.CertificateCount, true
}

// HasCertificateCount returns a boolean if a field has been set.
func (o *BursaTxInspection) HasCertificateCount() bool {
	if o != nil && !IsNil(o.CertificateCount) {
		return true
	}

	return false
}

// SetCertificateCount gets a reference to the given int32 and assigns it to the CertificateCount field.
func (o *BursaTxInspection) SetCertificateCount(v int32) {
	o.CertificateCount = &v
}

// GetEra returns the Era field value if set, zero value otherwise.
func (o *BursaTxInspection) GetEra() string {
	if o == nil || IsNil(o.Era) {
		var ret string
		return ret
	}
	return *o.Era
}

// GetEraOk returns a tuple with the Era field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetEraOk() (*string, bool) {
	if o == nil || IsNil(o.Era) {
		return nil, false
	}
	return o.Era, true
}

// HasEra returns a boolean if a field has been set.
func (o *BursaTxInspection) HasEra() bool {
	if o != nil && !IsNil(o.Era) {
		return true
	}

	return false
}

// SetEra gets a reference to the given string and assigns it to the Era field.
func (o *BursaTxInspection) SetEra(v string) {
	o.Era = &v
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *BursaTxInspection) GetFee() string {
	if o == nil || IsNil(o.Fee) {
		var ret string
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetFeeOk() (*string, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *BursaTxInspection) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given string and assigns it to the Fee field.
func (o *BursaTxInspection) SetFee(v string) {
	o.Fee = &v
}

// GetHasMetadata returns the HasMetadata field value if set, zero value otherwise.
func (o *BursaTxInspection) GetHasMetadata() bool {
	if o == nil || IsNil(o.HasMetadata) {
		var ret bool
		return ret
	}
	return *o.HasMetadata
}

// GetHasMetadataOk returns a tuple with the HasMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetHasMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMetadata) {
		return nil, false
	}
	return o.HasMetadata, true
}

// HasHasMetadata returns a boolean if a field has been set.
func (o *BursaTxInspection) HasHasMetadata() bool {
	if o != nil && !IsNil(o.HasMetadata) {
		return true
	}

	return false
}

// SetHasMetadata gets a reference to the given bool and assigns it to the HasMetadata field.
func (o *BursaTxInspection) SetHasMetadata(v bool) {
	o.HasMetadata = &v
}

// GetHasMint returns the HasMint field value if set, zero value otherwise.
func (o *BursaTxInspection) GetHasMint() bool {
	if o == nil || IsNil(o.HasMint) {
		var ret bool
		return ret
	}
	return *o.HasMint
}

// GetHasMintOk returns a tuple with the HasMint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetHasMintOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMint) {
		return nil, false
	}
	return o.HasMint, true
}

// HasHasMint returns a boolean if a field has been set.
func (o *BursaTxInspection) HasHasMint() bool {
	if o != nil && !IsNil(o.HasMint) {
		return true
	}

	return false
}

// SetHasMint gets a reference to the given bool and assigns it to the HasMint field.
func (o *BursaTxInspection) SetHasMint(v bool) {
	o.HasMint = &v
}

// GetHasTreasuryDonation returns the HasTreasuryDonation field value if set, zero value otherwise.
func (o *BursaTxInspection) GetHasTreasuryDonation() bool {
	if o == nil || IsNil(o.HasTreasuryDonation) {
		var ret bool
		return ret
	}
	return *o.HasTreasuryDonation
}

// GetHasTreasuryDonationOk returns a tuple with the HasTreasuryDonation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetHasTreasuryDonationOk() (*bool, bool) {
	if o == nil || IsNil(o.HasTreasuryDonation) {
		return nil, false
	}
	return o.HasTreasuryDonation, true
}

// HasHasTreasuryDonation returns a boolean if a field has been set.
func (o *BursaTxInspection) HasHasTreasuryDonation() bool {
	if o != nil && !IsNil(o.HasTreasuryDonation) {
		return true
	}

	return false
}

// SetHasTreasuryDonation gets a reference to the given bool and assigns it to the HasTreasuryDonation field.
func (o *BursaTxInspection) SetHasTreasuryDonation(v bool) {
	o.HasTreasuryDonation = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *BursaTxInspection) GetInputs() []BursaTxInput {
	if o == nil || IsNil(o.Inputs) {
		var ret []BursaTxInput
		return ret
	}
	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetInputsOk() ([]BursaTxInput, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *BursaTxInspection) HasInputs() bool {
	if o != nil && !IsNil(o.Inputs) {
		return true
	}

	return false
}

// SetInputs gets a reference to the given []BursaTxInput and assigns it to the Inputs field.
func (o *BursaTxInspection) SetInputs(v []BursaTxInput) {
	o.Inputs = v
}

// GetIsValid returns the IsValid field value if set, zero value otherwise.
func (o *BursaTxInspection) GetIsValid() bool {
	if o == nil || IsNil(o.IsValid) {
		var ret bool
		return ret
	}
	return *o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetIsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsValid) {
		return nil, false
	}
	return o.IsValid, true
}

// HasIsValid returns a boolean if a field has been set.
func (o *BursaTxInspection) HasIsValid() bool {
	if o != nil && !IsNil(o.IsValid) {
		return true
	}

	return false
}

// SetIsValid gets a reference to the given bool and assigns it to the IsValid field.
func (o *BursaTxInspection) SetIsValid(v bool) {
	o.IsValid = &v
}

// GetNativeScripts returns the NativeScripts field value if set, zero value otherwise.
func (o *BursaTxInspection) GetNativeScripts() int32 {
	if o == nil || IsNil(o.NativeScripts) {
		var ret int32
		return ret
	}
	return *o.NativeScripts
}

// GetNativeScriptsOk returns a tuple with the NativeScripts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetNativeScriptsOk() (*int32, bool) {
	if o == nil || IsNil(o.NativeScripts) {
		return nil, false
	}
	return o.NativeScripts, true
}

// HasNativeScripts returns a boolean if a field has been set.
func (o *BursaTxInspection) HasNativeScripts() bool {
	if o != nil && !IsNil(o.NativeScripts) {
		return true
	}

	return false
}

// SetNativeScripts gets a reference to the given int32 and assigns it to the NativeScripts field.
func (o *BursaTxInspection) SetNativeScripts(v int32) {
	o.NativeScripts = &v
}

// GetOutputs returns the Outputs field value if set, zero value otherwise.
func (o *BursaTxInspection) GetOutputs() []BursaTxOutput {
	if o == nil || IsNil(o.Outputs) {
		var ret []BursaTxOutput
		return ret
	}
	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetOutputsOk() ([]BursaTxOutput, bool) {
	if o == nil || IsNil(o.Outputs) {
		return nil, false
	}
	return o.Outputs, true
}

// HasOutputs returns a boolean if a field has been set.
func (o *BursaTxInspection) HasOutputs() bool {
	if o != nil && !IsNil(o.Outputs) {
		return true
	}

	return false
}

// SetOutputs gets a reference to the given []BursaTxOutput and assigns it to the Outputs field.
func (o *BursaTxInspection) SetOutputs(v []BursaTxOutput) {
	o.Outputs = v
}

// GetProposalProcedureCount returns the ProposalProcedureCount field value if set, zero value otherwise.
func (o *BursaTxInspection) GetProposalProcedureCount() int32 {
	if o == nil || IsNil(o.ProposalProcedureCount) {
		var ret int32
		return ret
	}
	return *o.ProposalProcedureCount
}

// GetProposalProcedureCountOk returns a tuple with the ProposalProcedureCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetProposalProcedureCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ProposalProcedureCount) {
		return nil, false
	}
	return o.ProposalProcedureCount, true
}

// HasProposalProcedureCount returns a boolean if a field has been set.
func (o *BursaTxInspection) HasProposalProcedureCount() bool {
	if o != nil && !IsNil(o.ProposalProcedureCount) {
		return true
	}

	return false
}

// SetProposalProcedureCount gets a reference to the given int32 and assigns it to the ProposalProcedureCount field.
func (o *BursaTxInspection) SetProposalProcedureCount(v int32) {
	o.ProposalProcedureCount = &v
}

// GetRequiredSigners returns the RequiredSigners field value if set, zero value otherwise.
func (o *BursaTxInspection) GetRequiredSigners() int32 {
	if o == nil || IsNil(o.RequiredSigners) {
		var ret int32
		return ret
	}
	return *o.RequiredSigners
}

// GetRequiredSignersOk returns a tuple with the RequiredSigners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetRequiredSignersOk() (*int32, bool) {
	if o == nil || IsNil(o.RequiredSigners) {
		return nil, false
	}
	return o.RequiredSigners, true
}

// HasRequiredSigners returns a boolean if a field has been set.
func (o *BursaTxInspection) HasRequiredSigners() bool {
	if o != nil && !IsNil(o.RequiredSigners) {
		return true
	}

	return false
}

// SetRequiredSigners gets a reference to the given int32 and assigns it to the RequiredSigners field.
func (o *BursaTxInspection) SetRequiredSigners(v int32) {
	o.RequiredSigners = &v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise.
func (o *BursaTxInspection) GetSizeBytes() int32 {
	if o == nil || IsNil(o.SizeBytes) {
		var ret int32
		return ret
	}
	return *o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetSizeBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeBytes) {
		return nil, false
	}
	return o.SizeBytes, true
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *BursaTxInspection) HasSizeBytes() bool {
	if o != nil && !IsNil(o.SizeBytes) {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given int32 and assigns it to the SizeBytes field.
func (o *BursaTxInspection) SetSizeBytes(v int32) {
	o.SizeBytes = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *BursaTxInspection) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *BursaTxInspection) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *BursaTxInspection) SetTtl(v int32) {
	o.Ttl = &v
}

// GetTxId returns the TxId field value if set, zero value otherwise.
func (o *BursaTxInspection) GetTxId() string {
	if o == nil || IsNil(o.TxId) {
		var ret string
		return ret
	}
	return *o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TxId) {
		return nil, false
	}
	return o.TxId, true
}

// HasTxId returns a boolean if a field has been set.
func (o *BursaTxInspection) HasTxId() bool {
	if o != nil && !IsNil(o.TxId) {
		return true
	}

	return false
}

// SetTxId gets a reference to the given string and assigns it to the TxId field.
func (o *BursaTxInspection) SetTxId(v string) {
	o.TxId = &v
}

// GetValidityIntervalStart returns the ValidityIntervalStart field value if set, zero value otherwise.
func (o *BursaTxInspection) GetValidityIntervalStart() int32 {
	if o == nil || IsNil(o.ValidityIntervalStart) {
		var ret int32
		return ret
	}
	return *o.ValidityIntervalStart
}

// GetValidityIntervalStartOk returns a tuple with the ValidityIntervalStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetValidityIntervalStartOk() (*int32, bool) {
	if o == nil || IsNil(o.ValidityIntervalStart) {
		return nil, false
	}
	return o.ValidityIntervalStart, true
}

// HasValidityIntervalStart returns a boolean if a field has been set.
func (o *BursaTxInspection) HasValidityIntervalStart() bool {
	if o != nil && !IsNil(o.ValidityIntervalStart) {
		return true
	}

	return false
}

// SetValidityIntervalStart gets a reference to the given int32 and assigns it to the ValidityIntervalStart field.
func (o *BursaTxInspection) SetValidityIntervalStart(v int32) {
	o.ValidityIntervalStart = &v
}

// GetVkeyWitnesses returns the VkeyWitnesses field value if set, zero value otherwise.
func (o *BursaTxInspection) GetVkeyWitnesses() int32 {
	if o == nil || IsNil(o.VkeyWitnesses) {
		var ret int32
		return ret
	}
	return *o.VkeyWitnesses
}

// GetVkeyWitnessesOk returns a tuple with the VkeyWitnesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetVkeyWitnessesOk() (*int32, bool) {
	if o == nil || IsNil(o.VkeyWitnesses) {
		return nil, false
	}
	return o.VkeyWitnesses, true
}

// HasVkeyWitnesses returns a boolean if a field has been set.
func (o *BursaTxInspection) HasVkeyWitnesses() bool {
	if o != nil && !IsNil(o.VkeyWitnesses) {
		return true
	}

	return false
}

// SetVkeyWitnesses gets a reference to the given int32 and assigns it to the VkeyWitnesses field.
func (o *BursaTxInspection) SetVkeyWitnesses(v int32) {
	o.VkeyWitnesses = &v
}

// GetVotingProcedureCount returns the VotingProcedureCount field value if set, zero value otherwise.
func (o *BursaTxInspection) GetVotingProcedureCount() int32 {
	if o == nil || IsNil(o.VotingProcedureCount) {
		var ret int32
		return ret
	}
	return *o.VotingProcedureCount
}

// GetVotingProcedureCountOk returns a tuple with the VotingProcedureCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetVotingProcedureCountOk() (*int32, bool) {
	if o == nil || IsNil(o.VotingProcedureCount) {
		return nil, false
	}
	return o.VotingProcedureCount, true
}

// HasVotingProcedureCount returns a boolean if a field has been set.
func (o *BursaTxInspection) HasVotingProcedureCount() bool {
	if o != nil && !IsNil(o.VotingProcedureCount) {
		return true
	}

	return false
}

// SetVotingProcedureCount gets a reference to the given int32 and assigns it to the VotingProcedureCount field.
func (o *BursaTxInspection) SetVotingProcedureCount(v int32) {
	o.VotingProcedureCount = &v
}

// GetWithdrawalCount returns the WithdrawalCount field value if set, zero value otherwise.
func (o *BursaTxInspection) GetWithdrawalCount() int32 {
	if o == nil || IsNil(o.WithdrawalCount) {
		var ret int32
		return ret
	}
	return *o.WithdrawalCount
}

// GetWithdrawalCountOk returns a tuple with the WithdrawalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxInspection) GetWithdrawalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.WithdrawalCount) {
		return nil, false
	}
	return o.WithdrawalCount, true
}

// HasWithdrawalCount returns a boolean if a field has been set.
func (o *BursaTxInspection) HasWithdrawalCount() bool {
	if o != nil && !IsNil(o.WithdrawalCount) {
		return true
	}

	return false
}

// SetWithdrawalCount gets a reference to the given int32 and assigns it to the WithdrawalCount field.
func (o *BursaTxInspection) SetWithdrawalCount(v int32) {
	o.WithdrawalCount = &v
}

func (o BursaTxInspection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BursaTxInspection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CertificateCount) {
		toSerialize["certificate_count"] = o.CertificateCount
	}
	if !IsNil(o.Era) {
		toSerialize["era"] = o.Era
	}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	if !IsNil(o.HasMetadata) {
		toSerialize["has_metadata"] = o.HasMetadata
	}
	if !IsNil(o.HasMint) {
		toSerialize["has_mint"] = o.HasMint
	}
	if !IsNil(o.HasTreasuryDonation) {
		toSerialize["has_treasury_donation"] = o.HasTreasuryDonation
	}
	if !IsNil(o.Inputs) {
		toSerialize["inputs"] = o.Inputs
	}
	if !IsNil(o.IsValid) {
		toSerialize["is_valid"] = o.IsValid
	}
	if !IsNil(o.NativeScripts) {
		toSerialize["native_scripts"] = o.NativeScripts
	}
	if !IsNil(o.Outputs) {
		toSerialize["outputs"] = o.Outputs
	}
	if !IsNil(o.ProposalProcedureCount) {
		toSerialize["proposal_procedure_count"] = o.ProposalProcedureCount
	}
	if !IsNil(o.RequiredSigners) {
		toSerialize["required_signers"] = o.RequiredSigners
	}
	if !IsNil(o.SizeBytes) {
		toSerialize["size_bytes"] = o.SizeBytes
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !IsNil(o.TxId) {
		toSerialize["tx_id"] = o.TxId
	}
	if !IsNil(o.ValidityIntervalStart) {
		toSerialize["validity_interval_start"] = o.ValidityIntervalStart
	}
	if !IsNil(o.VkeyWitnesses) {
		toSerialize["vkey_witnesses"] = o.VkeyWitnesses
	}
	if !IsNil(o.VotingProcedureCount) {
		toSerialize["voting_procedure_count"] = o.VotingProcedureCount
	}
	if !IsNil(o.WithdrawalCount) {
		toSerialize["withdrawal_count"] = o.WithdrawalCount
	}
	return toSerialize, nil
}

type NullableBursaTxInspection struct {
	value *BursaTxInspection
	isSet bool
}

func (v NullableBursaTxInspection) Get() *BursaTxInspection {
	return v.value
}

func (v *NullableBursaTxInspection) Set(val *BursaTxInspection) {
	v.value = val
	v.isSet = true
}

func (v NullableBursaTxInspection) IsSet() bool {
	return v.isSet
}

func (v *NullableBursaTxInspection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBursaTxInspection(val *BursaTxInspection) *NullableBursaTxInspection {
	return &NullableBursaTxInspection{value: val, isSet: true}
}

func (v NullableBursaTxInspection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBursaTxInspection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
