/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BursaTxOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BursaTxOutput{}

// BursaTxOutput struct for BursaTxOutput
type BursaTxOutput struct {
	Address *string `json:"address,omitempty"`
	// HasAssets is true when the output carries native (multi-)assets in addition to lovelace. The policy engine treats native-asset movement as a distinct, deny-by-default operation because lovelace limits do not bound token quantities.
	HasAssets *bool   `json:"has_assets,omitempty"`
	Lovelace  *string `json:"lovelace,omitempty"`
}

// NewBursaTxOutput instantiates a new BursaTxOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBursaTxOutput() *BursaTxOutput {
	this := BursaTxOutput{}
	return &this
}

// NewBursaTxOutputWithDefaults instantiates a new BursaTxOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBursaTxOutputWithDefaults() *BursaTxOutput {
	this := BursaTxOutput{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *BursaTxOutput) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxOutput) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *BursaTxOutput) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *BursaTxOutput) SetAddress(v string) {
	o.Address = &v
}

// GetHasAssets returns the HasAssets field value if set, zero value otherwise.
func (o *BursaTxOutput) GetHasAssets() bool {
	if o == nil || IsNil(o.HasAssets) {
		var ret bool
		return ret
	}
	return *o.HasAssets
}

// GetHasAssetsOk returns a tuple with the HasAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxOutput) GetHasAssetsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasAssets) {
		return nil, false
	}
	return o.HasAssets, true
}

// HasHasAssets returns a boolean if a field has been set.
func (o *BursaTxOutput) HasHasAssets() bool {
	if o != nil && !IsNil(o.HasAssets) {
		return true
	}

	return false
}

// SetHasAssets gets a reference to the given bool and assigns it to the HasAssets field.
func (o *BursaTxOutput) SetHasAssets(v bool) {
	o.HasAssets = &v
}

// GetLovelace returns the Lovelace field value if set, zero value otherwise.
func (o *BursaTxOutput) GetLovelace() string {
	if o == nil || IsNil(o.Lovelace) {
		var ret string
		return ret
	}
	return *o.Lovelace
}

// GetLovelaceOk returns a tuple with the Lovelace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaTxOutput) GetLovelaceOk() (*string, bool) {
	if o == nil || IsNil(o.Lovelace) {
		return nil, false
	}
	return o.Lovelace, true
}

// HasLovelace returns a boolean if a field has been set.
func (o *BursaTxOutput) HasLovelace() bool {
	if o != nil && !IsNil(o.Lovelace) {
		return true
	}

	return false
}

// SetLovelace gets a reference to the given string and assigns it to the Lovelace field.
func (o *BursaTxOutput) SetLovelace(v string) {
	o.Lovelace = &v
}

func (o BursaTxOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BursaTxOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.HasAssets) {
		toSerialize["has_assets"] = o.HasAssets
	}
	if !IsNil(o.Lovelace) {
		toSerialize["lovelace"] = o.Lovelace
	}
	return toSerialize, nil
}

type NullableBursaTxOutput struct {
	value *BursaTxOutput
	isSet bool
}

func (v NullableBursaTxOutput) Get() *BursaTxOutput {
	return v.value
}

func (v *NullableBursaTxOutput) Set(val *BursaTxOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableBursaTxOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableBursaTxOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBursaTxOutput(val *BursaTxOutput) *NullableBursaTxOutput {
	return &NullableBursaTxOutput{value: val, isSet: true}
}

func (v NullableBursaTxOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBursaTxOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
