/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiAddressParseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAddressParseRequest{}

// ApiAddressParseRequest struct for ApiAddressParseRequest
type ApiAddressParseRequest struct {
	Address string `json:"address"`
}

type _ApiAddressParseRequest ApiAddressParseRequest

// NewApiAddressParseRequest instantiates a new ApiAddressParseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAddressParseRequest(address string) *ApiAddressParseRequest {
	this := ApiAddressParseRequest{}
	this.Address = address
	return &this
}

// NewApiAddressParseRequestWithDefaults instantiates a new ApiAddressParseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAddressParseRequestWithDefaults() *ApiAddressParseRequest {
	this := ApiAddressParseRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *ApiAddressParseRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ApiAddressParseRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ApiAddressParseRequest) SetAddress(v string) {
	o.Address = v
}

func (o ApiAddressParseRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAddressParseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *ApiAddressParseRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiAddressParseRequest := _ApiAddressParseRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiAddressParseRequest)

	if err != nil {
		return err
	}

	*o = ApiAddressParseRequest(varApiAddressParseRequest)

	return err
}

type NullableApiAddressParseRequest struct {
	value *ApiAddressParseRequest
	isSet bool
}

func (v NullableApiAddressParseRequest) Get() *ApiAddressParseRequest {
	return v.value
}

func (v *NullableApiAddressParseRequest) Set(val *ApiAddressParseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAddressParseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAddressParseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAddressParseRequest(val *ApiAddressParseRequest) *NullableApiAddressParseRequest {
	return &NullableApiAddressParseRequest{value: val, isSet: true}
}

func (v NullableApiAddressParseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAddressParseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
