/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiTxDecodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxDecodeRequest{}

// ApiTxDecodeRequest struct for ApiTxDecodeRequest
type ApiTxDecodeRequest struct {
	// raw hex CBOR or JSON text envelope
	TxCbor string `json:"tx_cbor"`
}

type _ApiTxDecodeRequest ApiTxDecodeRequest

// NewApiTxDecodeRequest instantiates a new ApiTxDecodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxDecodeRequest(txCbor string) *ApiTxDecodeRequest {
	this := ApiTxDecodeRequest{}
	this.TxCbor = txCbor
	return &this
}

// NewApiTxDecodeRequestWithDefaults instantiates a new ApiTxDecodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxDecodeRequestWithDefaults() *ApiTxDecodeRequest {
	this := ApiTxDecodeRequest{}
	return &this
}

// GetTxCbor returns the TxCbor field value
func (o *ApiTxDecodeRequest) GetTxCbor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value
// and a boolean to check if the value has been set.
func (o *ApiTxDecodeRequest) GetTxCborOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxCbor, true
}

// SetTxCbor sets field value
func (o *ApiTxDecodeRequest) SetTxCbor(v string) {
	o.TxCbor = v
}

func (o ApiTxDecodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxDecodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tx_cbor"] = o.TxCbor
	return toSerialize, nil
}

func (o *ApiTxDecodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tx_cbor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTxDecodeRequest := _ApiTxDecodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTxDecodeRequest)

	if err != nil {
		return err
	}

	*o = ApiTxDecodeRequest(varApiTxDecodeRequest)

	return err
}

type NullableApiTxDecodeRequest struct {
	value *ApiTxDecodeRequest
	isSet bool
}

func (v NullableApiTxDecodeRequest) Get() *ApiTxDecodeRequest {
	return v.value
}

func (v *NullableApiTxDecodeRequest) Set(val *ApiTxDecodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxDecodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxDecodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxDecodeRequest(val *ApiTxDecodeRequest) *NullableApiTxDecodeRequest {
	return &NullableApiTxDecodeRequest{value: val, isSet: true}
}

func (v NullableApiTxDecodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxDecodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
