/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiAddressBuildRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAddressBuildRequest{}

// ApiAddressBuildRequest struct for ApiAddressBuildRequest
type ApiAddressBuildRequest struct {
	Network string `json:"network"`
	// bech32-encoded verification key (required for base and enterprise address types)
	PaymentKey *string `json:"paymentKey,omitempty"`
	// bech32-encoded verification key (required for base and reward address types)
	StakeKey *string `json:"stakeKey,omitempty"`
	// defaults to \"base\" - determines which keys are required: base requires both paymentKey and stakeKey, enterprise requires paymentKey only, reward requires stakeKey only
	Type *string `json:"type,omitempty"`
}

type _ApiAddressBuildRequest ApiAddressBuildRequest

// NewApiAddressBuildRequest instantiates a new ApiAddressBuildRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAddressBuildRequest(network string) *ApiAddressBuildRequest {
	this := ApiAddressBuildRequest{}
	this.Network = network
	return &this
}

// NewApiAddressBuildRequestWithDefaults instantiates a new ApiAddressBuildRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAddressBuildRequestWithDefaults() *ApiAddressBuildRequest {
	this := ApiAddressBuildRequest{}
	return &this
}

// GetNetwork returns the Network field value
func (o *ApiAddressBuildRequest) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildRequest) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *ApiAddressBuildRequest) SetNetwork(v string) {
	o.Network = v
}

// GetPaymentKey returns the PaymentKey field value if set, zero value otherwise.
func (o *ApiAddressBuildRequest) GetPaymentKey() string {
	if o == nil || IsNil(o.PaymentKey) {
		var ret string
		return ret
	}
	return *o.PaymentKey
}

// GetPaymentKeyOk returns a tuple with the PaymentKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildRequest) GetPaymentKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentKey) {
		return nil, false
	}
	return o.PaymentKey, true
}

// HasPaymentKey returns a boolean if a field has been set.
func (o *ApiAddressBuildRequest) HasPaymentKey() bool {
	if o != nil && !IsNil(o.PaymentKey) {
		return true
	}

	return false
}

// SetPaymentKey gets a reference to the given string and assigns it to the PaymentKey field.
func (o *ApiAddressBuildRequest) SetPaymentKey(v string) {
	o.PaymentKey = &v
}

// GetStakeKey returns the StakeKey field value if set, zero value otherwise.
func (o *ApiAddressBuildRequest) GetStakeKey() string {
	if o == nil || IsNil(o.StakeKey) {
		var ret string
		return ret
	}
	return *o.StakeKey
}

// GetStakeKeyOk returns a tuple with the StakeKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildRequest) GetStakeKeyOk() (*string, bool) {
	if o == nil || IsNil(o.StakeKey) {
		return nil, false
	}
	return o.StakeKey, true
}

// HasStakeKey returns a boolean if a field has been set.
func (o *ApiAddressBuildRequest) HasStakeKey() bool {
	if o != nil && !IsNil(o.StakeKey) {
		return true
	}

	return false
}

// SetStakeKey gets a reference to the given string and assigns it to the StakeKey field.
func (o *ApiAddressBuildRequest) SetStakeKey(v string) {
	o.StakeKey = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiAddressBuildRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiAddressBuildRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiAddressBuildRequest) SetType(v string) {
	o.Type = &v
}

func (o ApiAddressBuildRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAddressBuildRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	if !IsNil(o.PaymentKey) {
		toSerialize["paymentKey"] = o.PaymentKey
	}
	if !IsNil(o.StakeKey) {
		toSerialize["stakeKey"] = o.StakeKey
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *ApiAddressBuildRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiAddressBuildRequest := _ApiAddressBuildRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiAddressBuildRequest)

	if err != nil {
		return err
	}

	*o = ApiAddressBuildRequest(varApiAddressBuildRequest)

	return err
}

type NullableApiAddressBuildRequest struct {
	value *ApiAddressBuildRequest
	isSet bool
}

func (v NullableApiAddressBuildRequest) Get() *ApiAddressBuildRequest {
	return v.value
}

func (v *NullableApiAddressBuildRequest) Set(val *ApiAddressBuildRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAddressBuildRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAddressBuildRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAddressBuildRequest(val *ApiAddressBuildRequest) *NullableApiAddressBuildRequest {
	return &NullableApiAddressBuildRequest{value: val, isSet: true}
}

func (v NullableApiAddressBuildRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAddressBuildRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
