/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BursaEnumeratedAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BursaEnumeratedAddress{}

// BursaEnumeratedAddress struct for BursaEnumeratedAddress
type BursaEnumeratedAddress struct {
	Address *string `json:"address,omitempty"`
	Index   *int32  `json:"index,omitempty"`
}

// NewBursaEnumeratedAddress instantiates a new BursaEnumeratedAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBursaEnumeratedAddress() *BursaEnumeratedAddress {
	this := BursaEnumeratedAddress{}
	return &this
}

// NewBursaEnumeratedAddressWithDefaults instantiates a new BursaEnumeratedAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBursaEnumeratedAddressWithDefaults() *BursaEnumeratedAddress {
	this := BursaEnumeratedAddress{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *BursaEnumeratedAddress) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaEnumeratedAddress) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *BursaEnumeratedAddress) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *BursaEnumeratedAddress) SetAddress(v string) {
	o.Address = &v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *BursaEnumeratedAddress) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BursaEnumeratedAddress) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *BursaEnumeratedAddress) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *BursaEnumeratedAddress) SetIndex(v int32) {
	o.Index = &v
}

func (o BursaEnumeratedAddress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BursaEnumeratedAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	return toSerialize, nil
}

type NullableBursaEnumeratedAddress struct {
	value *BursaEnumeratedAddress
	isSet bool
}

func (v NullableBursaEnumeratedAddress) Get() *BursaEnumeratedAddress {
	return v.value
}

func (v *NullableBursaEnumeratedAddress) Set(val *BursaEnumeratedAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableBursaEnumeratedAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableBursaEnumeratedAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBursaEnumeratedAddress(val *BursaEnumeratedAddress) *NullableBursaEnumeratedAddress {
	return &NullableBursaEnumeratedAddress{value: val, isSet: true}
}

func (v NullableBursaEnumeratedAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBursaEnumeratedAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
