/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAddressBuildResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAddressBuildResponse{}

// ApiAddressBuildResponse struct for ApiAddressBuildResponse
type ApiAddressBuildResponse struct {
	Address *string `json:"address,omitempty"`
	Network *string `json:"network,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// NewApiAddressBuildResponse instantiates a new ApiAddressBuildResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAddressBuildResponse() *ApiAddressBuildResponse {
	this := ApiAddressBuildResponse{}
	return &this
}

// NewApiAddressBuildResponseWithDefaults instantiates a new ApiAddressBuildResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAddressBuildResponseWithDefaults() *ApiAddressBuildResponse {
	this := ApiAddressBuildResponse{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ApiAddressBuildResponse) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildResponse) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ApiAddressBuildResponse) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ApiAddressBuildResponse) SetAddress(v string) {
	o.Address = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *ApiAddressBuildResponse) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildResponse) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *ApiAddressBuildResponse) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *ApiAddressBuildResponse) SetNetwork(v string) {
	o.Network = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiAddressBuildResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressBuildResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiAddressBuildResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiAddressBuildResponse) SetType(v string) {
	o.Type = &v
}

func (o ApiAddressBuildResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAddressBuildResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiAddressBuildResponse struct {
	value *ApiAddressBuildResponse
	isSet bool
}

func (v NullableApiAddressBuildResponse) Get() *ApiAddressBuildResponse {
	return v.value
}

func (v *NullableApiAddressBuildResponse) Set(val *ApiAddressBuildResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAddressBuildResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAddressBuildResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAddressBuildResponse(val *ApiAddressBuildResponse) *NullableApiAddressBuildResponse {
	return &NullableApiAddressBuildResponse{value: val, isSet: true}
}

func (v NullableApiAddressBuildResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAddressBuildResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
