/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiAddressEnumerateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAddressEnumerateRequest{}

// ApiAddressEnumerateRequest struct for ApiAddressEnumerateRequest
type ApiAddressEnumerateRequest struct {
	Account  *int32  `json:"account,omitempty"`
	Count    int32   `json:"count"`
	Mnemonic string  `json:"mnemonic"`
	Network  string  `json:"network"`
	Password *string `json:"password,omitempty"`
	Start    *int32  `json:"start,omitempty"`
}

type _ApiAddressEnumerateRequest ApiAddressEnumerateRequest

// NewApiAddressEnumerateRequest instantiates a new ApiAddressEnumerateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAddressEnumerateRequest(count int32, mnemonic string, network string) *ApiAddressEnumerateRequest {
	this := ApiAddressEnumerateRequest{}
	this.Count = count
	this.Mnemonic = mnemonic
	this.Network = network
	return &this
}

// NewApiAddressEnumerateRequestWithDefaults instantiates a new ApiAddressEnumerateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAddressEnumerateRequestWithDefaults() *ApiAddressEnumerateRequest {
	this := ApiAddressEnumerateRequest{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ApiAddressEnumerateRequest) GetAccount() int32 {
	if o == nil || IsNil(o.Account) {
		var ret int32
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressEnumerateRequest) GetAccountOk() (*int32, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ApiAddressEnumerateRequest) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given int32 and assigns it to the Account field.
func (o *ApiAddressEnumerateRequest) SetAccount(v int32) {
	o.Account = &v
}

// GetCount returns the Count field value
func (o *ApiAddressEnumerateRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ApiAddressEnumerateRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ApiAddressEnumerateRequest) SetCount(v int32) {
	o.Count = v
}

// GetMnemonic returns the Mnemonic field value
func (o *ApiAddressEnumerateRequest) GetMnemonic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mnemonic
}

// GetMnemonicOk returns a tuple with the Mnemonic field value
// and a boolean to check if the value has been set.
func (o *ApiAddressEnumerateRequest) GetMnemonicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mnemonic, true
}

// SetMnemonic sets field value
func (o *ApiAddressEnumerateRequest) SetMnemonic(v string) {
	o.Mnemonic = v
}

// GetNetwork returns the Network field value
func (o *ApiAddressEnumerateRequest) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ApiAddressEnumerateRequest) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *ApiAddressEnumerateRequest) SetNetwork(v string) {
	o.Network = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ApiAddressEnumerateRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressEnumerateRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ApiAddressEnumerateRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ApiAddressEnumerateRequest) SetPassword(v string) {
	o.Password = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *ApiAddressEnumerateRequest) GetStart() int32 {
	if o == nil || IsNil(o.Start) {
		var ret int32
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressEnumerateRequest) GetStartOk() (*int32, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *ApiAddressEnumerateRequest) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given int32 and assigns it to the Start field.
func (o *ApiAddressEnumerateRequest) SetStart(v int32) {
	o.Start = &v
}

func (o ApiAddressEnumerateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAddressEnumerateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	toSerialize["count"] = o.Count
	toSerialize["mnemonic"] = o.Mnemonic
	toSerialize["network"] = o.Network
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	return toSerialize, nil
}

func (o *ApiAddressEnumerateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"mnemonic",
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiAddressEnumerateRequest := _ApiAddressEnumerateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiAddressEnumerateRequest)

	if err != nil {
		return err
	}

	*o = ApiAddressEnumerateRequest(varApiAddressEnumerateRequest)

	return err
}

type NullableApiAddressEnumerateRequest struct {
	value *ApiAddressEnumerateRequest
	isSet bool
}

func (v NullableApiAddressEnumerateRequest) Get() *ApiAddressEnumerateRequest {
	return v.value
}

func (v *NullableApiAddressEnumerateRequest) Set(val *ApiAddressEnumerateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAddressEnumerateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAddressEnumerateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAddressEnumerateRequest(val *ApiAddressEnumerateRequest) *NullableApiAddressEnumerateRequest {
	return &NullableApiAddressEnumerateRequest{value: val, isSet: true}
}

func (v NullableApiAddressEnumerateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAddressEnumerateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
