/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiTxWitnessRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxWitnessRequest{}

// ApiTxWitnessRequest struct for ApiTxWitnessRequest
type ApiTxWitnessRequest struct {
	SigningKey string `json:"signing_key"`
	// raw hex CBOR or JSON text envelope
	TxCbor string `json:"tx_cbor"`
}

type _ApiTxWitnessRequest ApiTxWitnessRequest

// NewApiTxWitnessRequest instantiates a new ApiTxWitnessRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxWitnessRequest(signingKey string, txCbor string) *ApiTxWitnessRequest {
	this := ApiTxWitnessRequest{}
	this.SigningKey = signingKey
	this.TxCbor = txCbor
	return &this
}

// NewApiTxWitnessRequestWithDefaults instantiates a new ApiTxWitnessRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxWitnessRequestWithDefaults() *ApiTxWitnessRequest {
	this := ApiTxWitnessRequest{}
	return &this
}

// GetSigningKey returns the SigningKey field value
func (o *ApiTxWitnessRequest) GetSigningKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningKey
}

// GetSigningKeyOk returns a tuple with the SigningKey field value
// and a boolean to check if the value has been set.
func (o *ApiTxWitnessRequest) GetSigningKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningKey, true
}

// SetSigningKey sets field value
func (o *ApiTxWitnessRequest) SetSigningKey(v string) {
	o.SigningKey = v
}

// GetTxCbor returns the TxCbor field value
func (o *ApiTxWitnessRequest) GetTxCbor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value
// and a boolean to check if the value has been set.
func (o *ApiTxWitnessRequest) GetTxCborOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxCbor, true
}

// SetTxCbor sets field value
func (o *ApiTxWitnessRequest) SetTxCbor(v string) {
	o.TxCbor = v
}

func (o ApiTxWitnessRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxWitnessRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signing_key"] = o.SigningKey
	toSerialize["tx_cbor"] = o.TxCbor
	return toSerialize, nil
}

func (o *ApiTxWitnessRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signing_key",
		"tx_cbor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTxWitnessRequest := _ApiTxWitnessRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTxWitnessRequest)

	if err != nil {
		return err
	}

	*o = ApiTxWitnessRequest(varApiTxWitnessRequest)

	return err
}

type NullableApiTxWitnessRequest struct {
	value *ApiTxWitnessRequest
	isSet bool
}

func (v NullableApiTxWitnessRequest) Get() *ApiTxWitnessRequest {
	return v.value
}

func (v *NullableApiTxWitnessRequest) Set(val *ApiTxWitnessRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxWitnessRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxWitnessRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxWitnessRequest(val *ApiTxWitnessRequest) *NullableApiTxWitnessRequest {
	return &NullableApiTxWitnessRequest{value: val, isSet: true}
}

func (v NullableApiTxWitnessRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxWitnessRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
