/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiWalletUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiWalletUpdateRequest{}

// ApiWalletUpdateRequest struct for ApiWalletUpdateRequest
type ApiWalletUpdateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Password    *string `json:"password,omitempty"`
}

type _ApiWalletUpdateRequest ApiWalletUpdateRequest

// NewApiWalletUpdateRequest instantiates a new ApiWalletUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWalletUpdateRequest(name string) *ApiWalletUpdateRequest {
	this := ApiWalletUpdateRequest{}
	this.Name = name
	return &this
}

// NewApiWalletUpdateRequestWithDefaults instantiates a new ApiWalletUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWalletUpdateRequestWithDefaults() *ApiWalletUpdateRequest {
	this := ApiWalletUpdateRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiWalletUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWalletUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiWalletUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiWalletUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *ApiWalletUpdateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiWalletUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiWalletUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ApiWalletUpdateRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWalletUpdateRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ApiWalletUpdateRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ApiWalletUpdateRequest) SetPassword(v string) {
	o.Password = &v
}

func (o ApiWalletUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiWalletUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

func (o *ApiWalletUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf(
				"no value given for required property %v",
				requiredProperty,
			)
		}
	}

	varApiWalletUpdateRequest := _ApiWalletUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiWalletUpdateRequest)

	if err != nil {
		return err
	}

	*o = ApiWalletUpdateRequest(varApiWalletUpdateRequest)

	return err
}

type NullableApiWalletUpdateRequest struct {
	value *ApiWalletUpdateRequest
	isSet bool
}

func (v NullableApiWalletUpdateRequest) Get() *ApiWalletUpdateRequest {
	return v.value
}

func (v *NullableApiWalletUpdateRequest) Set(val *ApiWalletUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWalletUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWalletUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWalletUpdateRequest(
	val *ApiWalletUpdateRequest,
) *NullableApiWalletUpdateRequest {
	return &NullableApiWalletUpdateRequest{value: val, isSet: true}
}

func (v NullableApiWalletUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWalletUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
