/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiTxSignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxSignRequest{}

// ApiTxSignRequest struct for ApiTxSignRequest
type ApiTxSignRequest struct {
	SigningKeys []string `json:"signing_keys"`
	// raw hex CBOR or JSON text envelope
	TxCbor string `json:"tx_cbor"`
}

type _ApiTxSignRequest ApiTxSignRequest

// NewApiTxSignRequest instantiates a new ApiTxSignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxSignRequest(signingKeys []string, txCbor string) *ApiTxSignRequest {
	this := ApiTxSignRequest{}
	this.SigningKeys = signingKeys
	this.TxCbor = txCbor
	return &this
}

// NewApiTxSignRequestWithDefaults instantiates a new ApiTxSignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxSignRequestWithDefaults() *ApiTxSignRequest {
	this := ApiTxSignRequest{}
	return &this
}

// GetSigningKeys returns the SigningKeys field value
func (o *ApiTxSignRequest) GetSigningKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SigningKeys
}

// GetSigningKeysOk returns a tuple with the SigningKeys field value
// and a boolean to check if the value has been set.
func (o *ApiTxSignRequest) GetSigningKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SigningKeys, true
}

// SetSigningKeys sets field value
func (o *ApiTxSignRequest) SetSigningKeys(v []string) {
	o.SigningKeys = v
}

// GetTxCbor returns the TxCbor field value
func (o *ApiTxSignRequest) GetTxCbor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value
// and a boolean to check if the value has been set.
func (o *ApiTxSignRequest) GetTxCborOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxCbor, true
}

// SetTxCbor sets field value
func (o *ApiTxSignRequest) SetTxCbor(v string) {
	o.TxCbor = v
}

func (o ApiTxSignRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxSignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signing_keys"] = o.SigningKeys
	toSerialize["tx_cbor"] = o.TxCbor
	return toSerialize, nil
}

func (o *ApiTxSignRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signing_keys",
		"tx_cbor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTxSignRequest := _ApiTxSignRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTxSignRequest)

	if err != nil {
		return err
	}

	*o = ApiTxSignRequest(varApiTxSignRequest)

	return err
}

type NullableApiTxSignRequest struct {
	value *ApiTxSignRequest
	isSet bool
}

func (v NullableApiTxSignRequest) Get() *ApiTxSignRequest {
	return v.value
}

func (v *NullableApiTxSignRequest) Set(val *ApiTxSignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxSignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxSignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxSignRequest(val *ApiTxSignRequest) *NullableApiTxSignRequest {
	return &NullableApiTxSignRequest{value: val, isSet: true}
}

func (v NullableApiTxSignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxSignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
