/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiVerifyDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiVerifyDataResponse{}

// ApiVerifyDataResponse struct for ApiVerifyDataResponse
type ApiVerifyDataResponse struct {
	Valid *bool `json:"valid,omitempty"`
}

// NewApiVerifyDataResponse instantiates a new ApiVerifyDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiVerifyDataResponse() *ApiVerifyDataResponse {
	this := ApiVerifyDataResponse{}
	return &this
}

// NewApiVerifyDataResponseWithDefaults instantiates a new ApiVerifyDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiVerifyDataResponseWithDefaults() *ApiVerifyDataResponse {
	this := ApiVerifyDataResponse{}
	return &this
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *ApiVerifyDataResponse) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVerifyDataResponse) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *ApiVerifyDataResponse) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *ApiVerifyDataResponse) SetValid(v bool) {
	o.Valid = &v
}

func (o ApiVerifyDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiVerifyDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	return toSerialize, nil
}

type NullableApiVerifyDataResponse struct {
	value *ApiVerifyDataResponse
	isSet bool
}

func (v NullableApiVerifyDataResponse) Get() *ApiVerifyDataResponse {
	return v.value
}

func (v *NullableApiVerifyDataResponse) Set(val *ApiVerifyDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiVerifyDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiVerifyDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiVerifyDataResponse(val *ApiVerifyDataResponse) *NullableApiVerifyDataResponse {
	return &NullableApiVerifyDataResponse{value: val, isSet: true}
}

func (v NullableApiVerifyDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiVerifyDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
