/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiScriptAddressResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiScriptAddressResponse{}

// ApiScriptAddressResponse struct for ApiScriptAddressResponse
type ApiScriptAddressResponse struct {
	Address    *string `json:"address,omitempty"`
	Network    *string `json:"network,omitempty"`
	ScriptHash *string `json:"scriptHash,omitempty"`
}

// NewApiScriptAddressResponse instantiates a new ApiScriptAddressResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiScriptAddressResponse() *ApiScriptAddressResponse {
	this := ApiScriptAddressResponse{}
	return &this
}

// NewApiScriptAddressResponseWithDefaults instantiates a new ApiScriptAddressResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiScriptAddressResponseWithDefaults() *ApiScriptAddressResponse {
	this := ApiScriptAddressResponse{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ApiScriptAddressResponse) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptAddressResponse) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ApiScriptAddressResponse) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ApiScriptAddressResponse) SetAddress(v string) {
	o.Address = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *ApiScriptAddressResponse) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptAddressResponse) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *ApiScriptAddressResponse) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *ApiScriptAddressResponse) SetNetwork(v string) {
	o.Network = &v
}

// GetScriptHash returns the ScriptHash field value if set, zero value otherwise.
func (o *ApiScriptAddressResponse) GetScriptHash() string {
	if o == nil || IsNil(o.ScriptHash) {
		var ret string
		return ret
	}
	return *o.ScriptHash
}

// GetScriptHashOk returns a tuple with the ScriptHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptAddressResponse) GetScriptHashOk() (*string, bool) {
	if o == nil || IsNil(o.ScriptHash) {
		return nil, false
	}
	return o.ScriptHash, true
}

// HasScriptHash returns a boolean if a field has been set.
func (o *ApiScriptAddressResponse) HasScriptHash() bool {
	if o != nil && !IsNil(o.ScriptHash) {
		return true
	}

	return false
}

// SetScriptHash gets a reference to the given string and assigns it to the ScriptHash field.
func (o *ApiScriptAddressResponse) SetScriptHash(v string) {
	o.ScriptHash = &v
}

func (o ApiScriptAddressResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiScriptAddressResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.ScriptHash) {
		toSerialize["scriptHash"] = o.ScriptHash
	}
	return toSerialize, nil
}

type NullableApiScriptAddressResponse struct {
	value *ApiScriptAddressResponse
	isSet bool
}

func (v NullableApiScriptAddressResponse) Get() *ApiScriptAddressResponse {
	return v.value
}

func (v *NullableApiScriptAddressResponse) Set(val *ApiScriptAddressResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiScriptAddressResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiScriptAddressResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiScriptAddressResponse(
	val *ApiScriptAddressResponse,
) *NullableApiScriptAddressResponse {
	return &NullableApiScriptAddressResponse{value: val, isSet: true}
}

func (v NullableApiScriptAddressResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiScriptAddressResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
