/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTxIDResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxIDResponse{}

// ApiTxIDResponse struct for ApiTxIDResponse
type ApiTxIDResponse struct {
	TxId *string `json:"tx_id,omitempty"`
}

// NewApiTxIDResponse instantiates a new ApiTxIDResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxIDResponse() *ApiTxIDResponse {
	this := ApiTxIDResponse{}
	return &this
}

// NewApiTxIDResponseWithDefaults instantiates a new ApiTxIDResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxIDResponseWithDefaults() *ApiTxIDResponse {
	this := ApiTxIDResponse{}
	return &this
}

// GetTxId returns the TxId field value if set, zero value otherwise.
func (o *ApiTxIDResponse) GetTxId() string {
	if o == nil || IsNil(o.TxId) {
		var ret string
		return ret
	}
	return *o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTxIDResponse) GetTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TxId) {
		return nil, false
	}
	return o.TxId, true
}

// HasTxId returns a boolean if a field has been set.
func (o *ApiTxIDResponse) HasTxId() bool {
	if o != nil && !IsNil(o.TxId) {
		return true
	}

	return false
}

// SetTxId gets a reference to the given string and assigns it to the TxId field.
func (o *ApiTxIDResponse) SetTxId(v string) {
	o.TxId = &v
}

func (o ApiTxIDResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxIDResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TxId) {
		toSerialize["tx_id"] = o.TxId
	}
	return toSerialize, nil
}

type NullableApiTxIDResponse struct {
	value *ApiTxIDResponse
	isSet bool
}

func (v NullableApiTxIDResponse) Get() *ApiTxIDResponse {
	return v.value
}

func (v *NullableApiTxIDResponse) Set(val *ApiTxIDResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxIDResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxIDResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxIDResponse(val *ApiTxIDResponse) *NullableApiTxIDResponse {
	return &NullableApiTxIDResponse{value: val, isSet: true}
}

func (v NullableApiTxIDResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxIDResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
