/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiSignDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSignDataResponse{}

// ApiSignDataResponse struct for ApiSignDataResponse
type ApiSignDataResponse struct {
	Key       *string `json:"key,omitempty"`
	Signature *string `json:"signature,omitempty"`
}

// NewApiSignDataResponse instantiates a new ApiSignDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSignDataResponse() *ApiSignDataResponse {
	this := ApiSignDataResponse{}
	return &this
}

// NewApiSignDataResponseWithDefaults instantiates a new ApiSignDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSignDataResponseWithDefaults() *ApiSignDataResponse {
	this := ApiSignDataResponse{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiSignDataResponse) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSignDataResponse) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiSignDataResponse) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ApiSignDataResponse) SetKey(v string) {
	o.Key = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *ApiSignDataResponse) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSignDataResponse) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *ApiSignDataResponse) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *ApiSignDataResponse) SetSignature(v string) {
	o.Signature = &v
}

func (o ApiSignDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSignDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	return toSerialize, nil
}

type NullableApiSignDataResponse struct {
	value *ApiSignDataResponse
	isSet bool
}

func (v NullableApiSignDataResponse) Get() *ApiSignDataResponse {
	return v.value
}

func (v *NullableApiSignDataResponse) Set(val *ApiSignDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSignDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSignDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSignDataResponse(val *ApiSignDataResponse) *NullableApiSignDataResponse {
	return &NullableApiSignDataResponse{value: val, isSet: true}
}

func (v NullableApiSignDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSignDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
