/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiPointerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiPointerInfo{}

// ApiPointerInfo struct for ApiPointerInfo
type ApiPointerInfo struct {
	CertIndex *int32 `json:"certIndex,omitempty"`
	Slot      *int64 `json:"slot,omitempty"`
	TxIndex   *int32 `json:"txIndex,omitempty"`
}

// NewApiPointerInfo instantiates a new ApiPointerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiPointerInfo() *ApiPointerInfo {
	this := ApiPointerInfo{}
	return &this
}

// NewApiPointerInfoWithDefaults instantiates a new ApiPointerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiPointerInfoWithDefaults() *ApiPointerInfo {
	this := ApiPointerInfo{}
	return &this
}

// GetCertIndex returns the CertIndex field value if set, zero value otherwise.
func (o *ApiPointerInfo) GetCertIndex() int32 {
	if o == nil || IsNil(o.CertIndex) {
		var ret int32
		return ret
	}
	return *o.CertIndex
}

// GetCertIndexOk returns a tuple with the CertIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPointerInfo) GetCertIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.CertIndex) {
		return nil, false
	}
	return o.CertIndex, true
}

// HasCertIndex returns a boolean if a field has been set.
func (o *ApiPointerInfo) HasCertIndex() bool {
	if o != nil && !IsNil(o.CertIndex) {
		return true
	}

	return false
}

// SetCertIndex gets a reference to the given int32 and assigns it to the CertIndex field.
func (o *ApiPointerInfo) SetCertIndex(v int32) {
	o.CertIndex = &v
}

// GetSlot returns the Slot field value if set, zero value otherwise.
func (o *ApiPointerInfo) GetSlot() int64 {
	if o == nil || IsNil(o.Slot) {
		var ret int64
		return ret
	}
	return *o.Slot
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPointerInfo) GetSlotOk() (*int64, bool) {
	if o == nil || IsNil(o.Slot) {
		return nil, false
	}
	return o.Slot, true
}

// HasSlot returns a boolean if a field has been set.
func (o *ApiPointerInfo) HasSlot() bool {
	if o != nil && !IsNil(o.Slot) {
		return true
	}

	return false
}

// SetSlot gets a reference to the given int64 and assigns it to the Slot field.
func (o *ApiPointerInfo) SetSlot(v int64) {
	o.Slot = &v
}

// GetTxIndex returns the TxIndex field value if set, zero value otherwise.
func (o *ApiPointerInfo) GetTxIndex() int32 {
	if o == nil || IsNil(o.TxIndex) {
		var ret int32
		return ret
	}
	return *o.TxIndex
}

// GetTxIndexOk returns a tuple with the TxIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPointerInfo) GetTxIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.TxIndex) {
		return nil, false
	}
	return o.TxIndex, true
}

// HasTxIndex returns a boolean if a field has been set.
func (o *ApiPointerInfo) HasTxIndex() bool {
	if o != nil && !IsNil(o.TxIndex) {
		return true
	}

	return false
}

// SetTxIndex gets a reference to the given int32 and assigns it to the TxIndex field.
func (o *ApiPointerInfo) SetTxIndex(v int32) {
	o.TxIndex = &v
}

func (o ApiPointerInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiPointerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CertIndex) {
		toSerialize["certIndex"] = o.CertIndex
	}
	if !IsNil(o.Slot) {
		toSerialize["slot"] = o.Slot
	}
	if !IsNil(o.TxIndex) {
		toSerialize["txIndex"] = o.TxIndex
	}
	return toSerialize, nil
}

type NullableApiPointerInfo struct {
	value *ApiPointerInfo
	isSet bool
}

func (v NullableApiPointerInfo) Get() *ApiPointerInfo {
	return v.value
}

func (v *NullableApiPointerInfo) Set(val *ApiPointerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableApiPointerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableApiPointerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiPointerInfo(val *ApiPointerInfo) *NullableApiPointerInfo {
	return &NullableApiPointerInfo{value: val, isSet: true}
}

func (v NullableApiPointerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiPointerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
