/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiScriptCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiScriptCreateRequest{}

// ApiScriptCreateRequest struct for ApiScriptCreateRequest
type ApiScriptCreateRequest struct {
	KeyHashes      []string `json:"key_hashes"`
	Network        string   `json:"network"`
	Required       *int32   `json:"required,omitempty"`
	TimelockAfter  *int64   `json:"timelock_after,omitempty"`
	TimelockBefore *int64   `json:"timelock_before,omitempty"`
	Type           string   `json:"type"`
}

type _ApiScriptCreateRequest ApiScriptCreateRequest

// NewApiScriptCreateRequest instantiates a new ApiScriptCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiScriptCreateRequest(
	keyHashes []string,
	network string,
	type_ string,
) *ApiScriptCreateRequest {
	this := ApiScriptCreateRequest{}
	this.KeyHashes = keyHashes
	this.Network = network
	this.Type = type_
	return &this
}

// NewApiScriptCreateRequestWithDefaults instantiates a new ApiScriptCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiScriptCreateRequestWithDefaults() *ApiScriptCreateRequest {
	this := ApiScriptCreateRequest{}
	return &this
}

// GetKeyHashes returns the KeyHashes field value
func (o *ApiScriptCreateRequest) GetKeyHashes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.KeyHashes
}

// GetKeyHashesOk returns a tuple with the KeyHashes field value
// and a boolean to check if the value has been set.
func (o *ApiScriptCreateRequest) GetKeyHashesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyHashes, true
}

// SetKeyHashes sets field value
func (o *ApiScriptCreateRequest) SetKeyHashes(v []string) {
	o.KeyHashes = v
}

// GetNetwork returns the Network field value
func (o *ApiScriptCreateRequest) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ApiScriptCreateRequest) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *ApiScriptCreateRequest) SetNetwork(v string) {
	o.Network = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *ApiScriptCreateRequest) GetRequired() int32 {
	if o == nil || IsNil(o.Required) {
		var ret int32
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptCreateRequest) GetRequiredOk() (*int32, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *ApiScriptCreateRequest) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given int32 and assigns it to the Required field.
func (o *ApiScriptCreateRequest) SetRequired(v int32) {
	o.Required = &v
}

// GetTimelockAfter returns the TimelockAfter field value if set, zero value otherwise.
func (o *ApiScriptCreateRequest) GetTimelockAfter() int64 {
	if o == nil || IsNil(o.TimelockAfter) {
		var ret int64
		return ret
	}
	return *o.TimelockAfter
}

// GetTimelockAfterOk returns a tuple with the TimelockAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptCreateRequest) GetTimelockAfterOk() (*int64, bool) {
	if o == nil || IsNil(o.TimelockAfter) {
		return nil, false
	}
	return o.TimelockAfter, true
}

// HasTimelockAfter returns a boolean if a field has been set.
func (o *ApiScriptCreateRequest) HasTimelockAfter() bool {
	if o != nil && !IsNil(o.TimelockAfter) {
		return true
	}

	return false
}

// SetTimelockAfter gets a reference to the given int64 and assigns it to the TimelockAfter field.
func (o *ApiScriptCreateRequest) SetTimelockAfter(v int64) {
	o.TimelockAfter = &v
}

// GetTimelockBefore returns the TimelockBefore field value if set, zero value otherwise.
func (o *ApiScriptCreateRequest) GetTimelockBefore() int64 {
	if o == nil || IsNil(o.TimelockBefore) {
		var ret int64
		return ret
	}
	return *o.TimelockBefore
}

// GetTimelockBeforeOk returns a tuple with the TimelockBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptCreateRequest) GetTimelockBeforeOk() (*int64, bool) {
	if o == nil || IsNil(o.TimelockBefore) {
		return nil, false
	}
	return o.TimelockBefore, true
}

// HasTimelockBefore returns a boolean if a field has been set.
func (o *ApiScriptCreateRequest) HasTimelockBefore() bool {
	if o != nil && !IsNil(o.TimelockBefore) {
		return true
	}

	return false
}

// SetTimelockBefore gets a reference to the given int64 and assigns it to the TimelockBefore field.
func (o *ApiScriptCreateRequest) SetTimelockBefore(v int64) {
	o.TimelockBefore = &v
}

// GetType returns the Type field value
func (o *ApiScriptCreateRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiScriptCreateRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiScriptCreateRequest) SetType(v string) {
	o.Type = v
}

func (o ApiScriptCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiScriptCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_hashes"] = o.KeyHashes
	toSerialize["network"] = o.Network
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.TimelockAfter) {
		toSerialize["timelock_after"] = o.TimelockAfter
	}
	if !IsNil(o.TimelockBefore) {
		toSerialize["timelock_before"] = o.TimelockBefore
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ApiScriptCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_hashes",
		"network",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf(
				"no value given for required property %v",
				requiredProperty,
			)
		}
	}

	varApiScriptCreateRequest := _ApiScriptCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiScriptCreateRequest)

	if err != nil {
		return err
	}

	*o = ApiScriptCreateRequest(varApiScriptCreateRequest)

	return err
}

type NullableApiScriptCreateRequest struct {
	value *ApiScriptCreateRequest
	isSet bool
}

func (v NullableApiScriptCreateRequest) Get() *ApiScriptCreateRequest {
	return v.value
}

func (v *NullableApiScriptCreateRequest) Set(val *ApiScriptCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiScriptCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiScriptCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiScriptCreateRequest(
	val *ApiScriptCreateRequest,
) *NullableApiScriptCreateRequest {
	return &NullableApiScriptCreateRequest{value: val, isSet: true}
}

func (v NullableApiScriptCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiScriptCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
