/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiWalletGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiWalletGetRequest{}

// ApiWalletGetRequest struct for ApiWalletGetRequest
type ApiWalletGetRequest struct {
	Name     string  `json:"name"`
	Password *string `json:"password,omitempty"`
}

type _ApiWalletGetRequest ApiWalletGetRequest

// NewApiWalletGetRequest instantiates a new ApiWalletGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWalletGetRequest(name string) *ApiWalletGetRequest {
	this := ApiWalletGetRequest{}
	this.Name = name
	return &this
}

// NewApiWalletGetRequestWithDefaults instantiates a new ApiWalletGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWalletGetRequestWithDefaults() *ApiWalletGetRequest {
	this := ApiWalletGetRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ApiWalletGetRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiWalletGetRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiWalletGetRequest) SetName(v string) {
	o.Name = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ApiWalletGetRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWalletGetRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ApiWalletGetRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ApiWalletGetRequest) SetPassword(v string) {
	o.Password = &v
}

func (o ApiWalletGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiWalletGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

func (o *ApiWalletGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf(
				"no value given for required property %v",
				requiredProperty,
			)
		}
	}

	varApiWalletGetRequest := _ApiWalletGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiWalletGetRequest)

	if err != nil {
		return err
	}

	*o = ApiWalletGetRequest(varApiWalletGetRequest)

	return err
}

type NullableApiWalletGetRequest struct {
	value *ApiWalletGetRequest
	isSet bool
}

func (v NullableApiWalletGetRequest) Get() *ApiWalletGetRequest {
	return v.value
}

func (v *NullableApiWalletGetRequest) Set(val *ApiWalletGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWalletGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWalletGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWalletGetRequest(
	val *ApiWalletGetRequest,
) *NullableApiWalletGetRequest {
	return &NullableApiWalletGetRequest{value: val, isSet: true}
}

func (v NullableApiWalletGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWalletGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
