/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiTxIDRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxIDRequest{}

// ApiTxIDRequest struct for ApiTxIDRequest
type ApiTxIDRequest struct {
	// raw hex CBOR or JSON text envelope
	TxCbor string `json:"tx_cbor"`
}

type _ApiTxIDRequest ApiTxIDRequest

// NewApiTxIDRequest instantiates a new ApiTxIDRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxIDRequest(txCbor string) *ApiTxIDRequest {
	this := ApiTxIDRequest{}
	this.TxCbor = txCbor
	return &this
}

// NewApiTxIDRequestWithDefaults instantiates a new ApiTxIDRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxIDRequestWithDefaults() *ApiTxIDRequest {
	this := ApiTxIDRequest{}
	return &this
}

// GetTxCbor returns the TxCbor field value
func (o *ApiTxIDRequest) GetTxCbor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value
// and a boolean to check if the value has been set.
func (o *ApiTxIDRequest) GetTxCborOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxCbor, true
}

// SetTxCbor sets field value
func (o *ApiTxIDRequest) SetTxCbor(v string) {
	o.TxCbor = v
}

func (o ApiTxIDRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxIDRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tx_cbor"] = o.TxCbor
	return toSerialize, nil
}

func (o *ApiTxIDRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tx_cbor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTxIDRequest := _ApiTxIDRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTxIDRequest)

	if err != nil {
		return err
	}

	*o = ApiTxIDRequest(varApiTxIDRequest)

	return err
}

type NullableApiTxIDRequest struct {
	value *ApiTxIDRequest
	isSet bool
}

func (v NullableApiTxIDRequest) Get() *ApiTxIDRequest {
	return v.value
}

func (v *NullableApiTxIDRequest) Set(val *ApiTxIDRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxIDRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxIDRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxIDRequest(val *ApiTxIDRequest) *NullableApiTxIDRequest {
	return &NullableApiTxIDRequest{value: val, isSet: true}
}

func (v NullableApiTxIDRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxIDRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
