/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiScriptResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiScriptResponse{}

// ApiScriptResponse struct for ApiScriptResponse
type ApiScriptResponse struct {
	Address    *string                           `json:"address,omitempty"`
	Script     map[string]map[string]interface{} `json:"script,omitempty"`
	ScriptHash *string                           `json:"scriptHash,omitempty"`
	Type       *string                           `json:"type,omitempty"`
}

// NewApiScriptResponse instantiates a new ApiScriptResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiScriptResponse() *ApiScriptResponse {
	this := ApiScriptResponse{}
	return &this
}

// NewApiScriptResponseWithDefaults instantiates a new ApiScriptResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiScriptResponseWithDefaults() *ApiScriptResponse {
	this := ApiScriptResponse{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ApiScriptResponse) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptResponse) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ApiScriptResponse) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ApiScriptResponse) SetAddress(v string) {
	o.Address = &v
}

// GetScript returns the Script field value if set, zero value otherwise.
func (o *ApiScriptResponse) GetScript() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Script) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Script
}

// GetScriptOk returns a tuple with the Script field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptResponse) GetScriptOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Script) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Script, true
}

// HasScript returns a boolean if a field has been set.
func (o *ApiScriptResponse) HasScript() bool {
	if o != nil && !IsNil(o.Script) {
		return true
	}

	return false
}

// SetScript gets a reference to the given map[string]map[string]interface{} and assigns it to the Script field.
func (o *ApiScriptResponse) SetScript(v map[string]map[string]interface{}) {
	o.Script = v
}

// GetScriptHash returns the ScriptHash field value if set, zero value otherwise.
func (o *ApiScriptResponse) GetScriptHash() string {
	if o == nil || IsNil(o.ScriptHash) {
		var ret string
		return ret
	}
	return *o.ScriptHash
}

// GetScriptHashOk returns a tuple with the ScriptHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptResponse) GetScriptHashOk() (*string, bool) {
	if o == nil || IsNil(o.ScriptHash) {
		return nil, false
	}
	return o.ScriptHash, true
}

// HasScriptHash returns a boolean if a field has been set.
func (o *ApiScriptResponse) HasScriptHash() bool {
	if o != nil && !IsNil(o.ScriptHash) {
		return true
	}

	return false
}

// SetScriptHash gets a reference to the given string and assigns it to the ScriptHash field.
func (o *ApiScriptResponse) SetScriptHash(v string) {
	o.ScriptHash = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiScriptResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiScriptResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiScriptResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiScriptResponse) SetType(v string) {
	o.Type = &v
}

func (o ApiScriptResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiScriptResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Script) {
		toSerialize["script"] = o.Script
	}
	if !IsNil(o.ScriptHash) {
		toSerialize["scriptHash"] = o.ScriptHash
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiScriptResponse struct {
	value *ApiScriptResponse
	isSet bool
}

func (v NullableApiScriptResponse) Get() *ApiScriptResponse {
	return v.value
}

func (v *NullableApiScriptResponse) Set(val *ApiScriptResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiScriptResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiScriptResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiScriptResponse(
	val *ApiScriptResponse,
) *NullableApiScriptResponse {
	return &NullableApiScriptResponse{value: val, isSet: true}
}

func (v NullableApiScriptResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiScriptResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
