/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTxCborResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxCborResponse{}

// ApiTxCborResponse struct for ApiTxCborResponse
type ApiTxCborResponse struct {
	TxCbor *string `json:"tx_cbor,omitempty"`
	TxId   *string `json:"tx_id,omitempty"`
}

// NewApiTxCborResponse instantiates a new ApiTxCborResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxCborResponse() *ApiTxCborResponse {
	this := ApiTxCborResponse{}
	return &this
}

// NewApiTxCborResponseWithDefaults instantiates a new ApiTxCborResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxCborResponseWithDefaults() *ApiTxCborResponse {
	this := ApiTxCborResponse{}
	return &this
}

// GetTxCbor returns the TxCbor field value if set, zero value otherwise.
func (o *ApiTxCborResponse) GetTxCbor() string {
	if o == nil || IsNil(o.TxCbor) {
		var ret string
		return ret
	}
	return *o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTxCborResponse) GetTxCborOk() (*string, bool) {
	if o == nil || IsNil(o.TxCbor) {
		return nil, false
	}
	return o.TxCbor, true
}

// HasTxCbor returns a boolean if a field has been set.
func (o *ApiTxCborResponse) HasTxCbor() bool {
	if o != nil && !IsNil(o.TxCbor) {
		return true
	}

	return false
}

// SetTxCbor gets a reference to the given string and assigns it to the TxCbor field.
func (o *ApiTxCborResponse) SetTxCbor(v string) {
	o.TxCbor = &v
}

// GetTxId returns the TxId field value if set, zero value otherwise.
func (o *ApiTxCborResponse) GetTxId() string {
	if o == nil || IsNil(o.TxId) {
		var ret string
		return ret
	}
	return *o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTxCborResponse) GetTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TxId) {
		return nil, false
	}
	return o.TxId, true
}

// HasTxId returns a boolean if a field has been set.
func (o *ApiTxCborResponse) HasTxId() bool {
	if o != nil && !IsNil(o.TxId) {
		return true
	}

	return false
}

// SetTxId gets a reference to the given string and assigns it to the TxId field.
func (o *ApiTxCborResponse) SetTxId(v string) {
	o.TxId = &v
}

func (o ApiTxCborResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxCborResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TxCbor) {
		toSerialize["tx_cbor"] = o.TxCbor
	}
	if !IsNil(o.TxId) {
		toSerialize["tx_id"] = o.TxId
	}
	return toSerialize, nil
}

type NullableApiTxCborResponse struct {
	value *ApiTxCborResponse
	isSet bool
}

func (v NullableApiTxCborResponse) Get() *ApiTxCborResponse {
	return v.value
}

func (v *NullableApiTxCborResponse) Set(val *ApiTxCborResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxCborResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxCborResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxCborResponse(val *ApiTxCborResponse) *NullableApiTxCborResponse {
	return &NullableApiTxCborResponse{value: val, isSet: true}
}

func (v NullableApiTxCborResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxCborResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
