/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiByronAddressInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiByronAddressInfo{}

// ApiByronAddressInfo struct for ApiByronAddressInfo
type ApiByronAddressInfo struct {
	// \"pubkey\", \"script\", or \"redeem\"
	Type *string `json:"type,omitempty"`
}

// NewApiByronAddressInfo instantiates a new ApiByronAddressInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiByronAddressInfo() *ApiByronAddressInfo {
	this := ApiByronAddressInfo{}
	return &this
}

// NewApiByronAddressInfoWithDefaults instantiates a new ApiByronAddressInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiByronAddressInfoWithDefaults() *ApiByronAddressInfo {
	this := ApiByronAddressInfo{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiByronAddressInfo) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiByronAddressInfo) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiByronAddressInfo) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiByronAddressInfo) SetType(v string) {
	o.Type = &v
}

func (o ApiByronAddressInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiByronAddressInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiByronAddressInfo struct {
	value *ApiByronAddressInfo
	isSet bool
}

func (v NullableApiByronAddressInfo) Get() *ApiByronAddressInfo {
	return v.value
}

func (v *NullableApiByronAddressInfo) Set(val *ApiByronAddressInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableApiByronAddressInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableApiByronAddressInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiByronAddressInfo(val *ApiByronAddressInfo) *NullableApiByronAddressInfo {
	return &NullableApiByronAddressInfo{value: val, isSet: true}
}

func (v NullableApiByronAddressInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiByronAddressInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
