/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAddressParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAddressParseResponse{}

// ApiAddressParseResponse struct for ApiAddressParseResponse
type ApiAddressParseResponse struct {
	Address         *string              `json:"address,omitempty"`
	Byron           *ApiByronAddressInfo `json:"byron,omitempty"`
	Network         *string              `json:"network,omitempty"`
	Payment         *ApiCredentialInfo   `json:"payment,omitempty"`
	Pointer         *ApiPointerInfo      `json:"pointer,omitempty"`
	Stake           *ApiCredentialInfo   `json:"stake,omitempty"`
	Type            *string              `json:"type,omitempty"`
	TypeDescription *string              `json:"typeDescription,omitempty"`
}

// NewApiAddressParseResponse instantiates a new ApiAddressParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAddressParseResponse() *ApiAddressParseResponse {
	this := ApiAddressParseResponse{}
	return &this
}

// NewApiAddressParseResponseWithDefaults instantiates a new ApiAddressParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAddressParseResponseWithDefaults() *ApiAddressParseResponse {
	this := ApiAddressParseResponse{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ApiAddressParseResponse) SetAddress(v string) {
	o.Address = &v
}

// GetByron returns the Byron field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetByron() ApiByronAddressInfo {
	if o == nil || IsNil(o.Byron) {
		var ret ApiByronAddressInfo
		return ret
	}
	return *o.Byron
}

// GetByronOk returns a tuple with the Byron field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetByronOk() (*ApiByronAddressInfo, bool) {
	if o == nil || IsNil(o.Byron) {
		return nil, false
	}
	return o.Byron, true
}

// HasByron returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasByron() bool {
	if o != nil && !IsNil(o.Byron) {
		return true
	}

	return false
}

// SetByron gets a reference to the given ApiByronAddressInfo and assigns it to the Byron field.
func (o *ApiAddressParseResponse) SetByron(v ApiByronAddressInfo) {
	o.Byron = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *ApiAddressParseResponse) SetNetwork(v string) {
	o.Network = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetPayment() ApiCredentialInfo {
	if o == nil || IsNil(o.Payment) {
		var ret ApiCredentialInfo
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetPaymentOk() (*ApiCredentialInfo, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given ApiCredentialInfo and assigns it to the Payment field.
func (o *ApiAddressParseResponse) SetPayment(v ApiCredentialInfo) {
	o.Payment = &v
}

// GetPointer returns the Pointer field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetPointer() ApiPointerInfo {
	if o == nil || IsNil(o.Pointer) {
		var ret ApiPointerInfo
		return ret
	}
	return *o.Pointer
}

// GetPointerOk returns a tuple with the Pointer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetPointerOk() (*ApiPointerInfo, bool) {
	if o == nil || IsNil(o.Pointer) {
		return nil, false
	}
	return o.Pointer, true
}

// HasPointer returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasPointer() bool {
	if o != nil && !IsNil(o.Pointer) {
		return true
	}

	return false
}

// SetPointer gets a reference to the given ApiPointerInfo and assigns it to the Pointer field.
func (o *ApiAddressParseResponse) SetPointer(v ApiPointerInfo) {
	o.Pointer = &v
}

// GetStake returns the Stake field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetStake() ApiCredentialInfo {
	if o == nil || IsNil(o.Stake) {
		var ret ApiCredentialInfo
		return ret
	}
	return *o.Stake
}

// GetStakeOk returns a tuple with the Stake field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetStakeOk() (*ApiCredentialInfo, bool) {
	if o == nil || IsNil(o.Stake) {
		return nil, false
	}
	return o.Stake, true
}

// HasStake returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasStake() bool {
	if o != nil && !IsNil(o.Stake) {
		return true
	}

	return false
}

// SetStake gets a reference to the given ApiCredentialInfo and assigns it to the Stake field.
func (o *ApiAddressParseResponse) SetStake(v ApiCredentialInfo) {
	o.Stake = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiAddressParseResponse) SetType(v string) {
	o.Type = &v
}

// GetTypeDescription returns the TypeDescription field value if set, zero value otherwise.
func (o *ApiAddressParseResponse) GetTypeDescription() string {
	if o == nil || IsNil(o.TypeDescription) {
		var ret string
		return ret
	}
	return *o.TypeDescription
}

// GetTypeDescriptionOk returns a tuple with the TypeDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddressParseResponse) GetTypeDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeDescription) {
		return nil, false
	}
	return o.TypeDescription, true
}

// HasTypeDescription returns a boolean if a field has been set.
func (o *ApiAddressParseResponse) HasTypeDescription() bool {
	if o != nil && !IsNil(o.TypeDescription) {
		return true
	}

	return false
}

// SetTypeDescription gets a reference to the given string and assigns it to the TypeDescription field.
func (o *ApiAddressParseResponse) SetTypeDescription(v string) {
	o.TypeDescription = &v
}

func (o ApiAddressParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAddressParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Byron) {
		toSerialize["byron"] = o.Byron
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.Pointer) {
		toSerialize["pointer"] = o.Pointer
	}
	if !IsNil(o.Stake) {
		toSerialize["stake"] = o.Stake
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.TypeDescription) {
		toSerialize["typeDescription"] = o.TypeDescription
	}
	return toSerialize, nil
}

type NullableApiAddressParseResponse struct {
	value *ApiAddressParseResponse
	isSet bool
}

func (v NullableApiAddressParseResponse) Get() *ApiAddressParseResponse {
	return v.value
}

func (v *NullableApiAddressParseResponse) Set(val *ApiAddressParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAddressParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAddressParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAddressParseResponse(val *ApiAddressParseResponse) *NullableApiAddressParseResponse {
	return &NullableApiAddressParseResponse{value: val, isSet: true}
}

func (v NullableApiAddressParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAddressParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
