/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiSignDataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSignDataRequest{}

// ApiSignDataRequest struct for ApiSignDataRequest
type ApiSignDataRequest struct {
	Address    string `json:"address"`
	Payload    string `json:"payload"`
	SigningKey string `json:"signing_key"`
}

type _ApiSignDataRequest ApiSignDataRequest

// NewApiSignDataRequest instantiates a new ApiSignDataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSignDataRequest(address string, payload string, signingKey string) *ApiSignDataRequest {
	this := ApiSignDataRequest{}
	this.Address = address
	this.Payload = payload
	this.SigningKey = signingKey
	return &this
}

// NewApiSignDataRequestWithDefaults instantiates a new ApiSignDataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSignDataRequestWithDefaults() *ApiSignDataRequest {
	this := ApiSignDataRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *ApiSignDataRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ApiSignDataRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ApiSignDataRequest) SetAddress(v string) {
	o.Address = v
}

// GetPayload returns the Payload field value
func (o *ApiSignDataRequest) GetPayload() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *ApiSignDataRequest) GetPayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *ApiSignDataRequest) SetPayload(v string) {
	o.Payload = v
}

// GetSigningKey returns the SigningKey field value
func (o *ApiSignDataRequest) GetSigningKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningKey
}

// GetSigningKeyOk returns a tuple with the SigningKey field value
// and a boolean to check if the value has been set.
func (o *ApiSignDataRequest) GetSigningKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningKey, true
}

// SetSigningKey sets field value
func (o *ApiSignDataRequest) SetSigningKey(v string) {
	o.SigningKey = v
}

func (o ApiSignDataRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSignDataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["payload"] = o.Payload
	toSerialize["signing_key"] = o.SigningKey
	return toSerialize, nil
}

func (o *ApiSignDataRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"payload",
		"signing_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiSignDataRequest := _ApiSignDataRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiSignDataRequest)

	if err != nil {
		return err
	}

	*o = ApiSignDataRequest(varApiSignDataRequest)

	return err
}

type NullableApiSignDataRequest struct {
	value *ApiSignDataRequest
	isSet bool
}

func (v NullableApiSignDataRequest) Get() *ApiSignDataRequest {
	return v.value
}

func (v *NullableApiSignDataRequest) Set(val *ApiSignDataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSignDataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSignDataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSignDataRequest(val *ApiSignDataRequest) *NullableApiSignDataRequest {
	return &NullableApiSignDataRequest{value: val, isSet: true}
}

func (v NullableApiSignDataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSignDataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
