/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiTxAssembleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxAssembleRequest{}

// ApiTxAssembleRequest struct for ApiTxAssembleRequest
type ApiTxAssembleRequest struct {
	// raw hex CBOR or JSON text envelope
	TxCbor    string   `json:"tx_cbor"`
	Witnesses []string `json:"witnesses"`
}

type _ApiTxAssembleRequest ApiTxAssembleRequest

// NewApiTxAssembleRequest instantiates a new ApiTxAssembleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxAssembleRequest(txCbor string, witnesses []string) *ApiTxAssembleRequest {
	this := ApiTxAssembleRequest{}
	this.TxCbor = txCbor
	this.Witnesses = witnesses
	return &this
}

// NewApiTxAssembleRequestWithDefaults instantiates a new ApiTxAssembleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxAssembleRequestWithDefaults() *ApiTxAssembleRequest {
	this := ApiTxAssembleRequest{}
	return &this
}

// GetTxCbor returns the TxCbor field value
func (o *ApiTxAssembleRequest) GetTxCbor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value
// and a boolean to check if the value has been set.
func (o *ApiTxAssembleRequest) GetTxCborOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxCbor, true
}

// SetTxCbor sets field value
func (o *ApiTxAssembleRequest) SetTxCbor(v string) {
	o.TxCbor = v
}

// GetWitnesses returns the Witnesses field value
func (o *ApiTxAssembleRequest) GetWitnesses() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Witnesses
}

// GetWitnessesOk returns a tuple with the Witnesses field value
// and a boolean to check if the value has been set.
func (o *ApiTxAssembleRequest) GetWitnessesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Witnesses, true
}

// SetWitnesses sets field value
func (o *ApiTxAssembleRequest) SetWitnesses(v []string) {
	o.Witnesses = v
}

func (o ApiTxAssembleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxAssembleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tx_cbor"] = o.TxCbor
	toSerialize["witnesses"] = o.Witnesses
	return toSerialize, nil
}

func (o *ApiTxAssembleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tx_cbor",
		"witnesses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTxAssembleRequest := _ApiTxAssembleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTxAssembleRequest)

	if err != nil {
		return err
	}

	*o = ApiTxAssembleRequest(varApiTxAssembleRequest)

	return err
}

type NullableApiTxAssembleRequest struct {
	value *ApiTxAssembleRequest
	isSet bool
}

func (v NullableApiTxAssembleRequest) Get() *ApiTxAssembleRequest {
	return v.value
}

func (v *NullableApiTxAssembleRequest) Set(val *ApiTxAssembleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxAssembleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxAssembleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxAssembleRequest(val *ApiTxAssembleRequest) *NullableApiTxAssembleRequest {
	return &NullableApiTxAssembleRequest{value: val, isSet: true}
}

func (v NullableApiTxAssembleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxAssembleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
