/*
bursa

Programmable Cardano Wallet API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTxWitnessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxWitnessResponse{}

// ApiTxWitnessResponse struct for ApiTxWitnessResponse
type ApiTxWitnessResponse struct {
	Witness *string `json:"witness,omitempty"`
}

// NewApiTxWitnessResponse instantiates a new ApiTxWitnessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxWitnessResponse() *ApiTxWitnessResponse {
	this := ApiTxWitnessResponse{}
	return &this
}

// NewApiTxWitnessResponseWithDefaults instantiates a new ApiTxWitnessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxWitnessResponseWithDefaults() *ApiTxWitnessResponse {
	this := ApiTxWitnessResponse{}
	return &this
}

// GetWitness returns the Witness field value if set, zero value otherwise.
func (o *ApiTxWitnessResponse) GetWitness() string {
	if o == nil || IsNil(o.Witness) {
		var ret string
		return ret
	}
	return *o.Witness
}

// GetWitnessOk returns a tuple with the Witness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTxWitnessResponse) GetWitnessOk() (*string, bool) {
	if o == nil || IsNil(o.Witness) {
		return nil, false
	}
	return o.Witness, true
}

// HasWitness returns a boolean if a field has been set.
func (o *ApiTxWitnessResponse) HasWitness() bool {
	if o != nil && !IsNil(o.Witness) {
		return true
	}

	return false
}

// SetWitness gets a reference to the given string and assigns it to the Witness field.
func (o *ApiTxWitnessResponse) SetWitness(v string) {
	o.Witness = &v
}

func (o ApiTxWitnessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxWitnessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Witness) {
		toSerialize["witness"] = o.Witness
	}
	return toSerialize, nil
}

type NullableApiTxWitnessResponse struct {
	value *ApiTxWitnessResponse
	isSet bool
}

func (v NullableApiTxWitnessResponse) Get() *ApiTxWitnessResponse {
	return v.value
}

func (v *NullableApiTxWitnessResponse) Set(val *ApiTxWitnessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxWitnessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxWitnessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxWitnessResponse(val *ApiTxWitnessResponse) *NullableApiTxWitnessResponse {
	return &NullableApiTxWitnessResponse{value: val, isSet: true}
}

func (v NullableApiTxWitnessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxWitnessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
