openapi: 3.0.1
info:
  contact:
    email: support@blinklabs.io
    name: Blink Labs
    url: https://blinklabs.io
  description: Programmable Cardano Wallet API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: bursa
  version: v0
servers:
- url: /
paths:
  /api/wallet/create:
    get:
      description: Create a wallet and return details
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bursa.Wallet"
          description: Ok
      summary: Create a wallet
  /api/wallet/delete:
    post:
      description: Deletes a wallet from persistent storage and optional password.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api.WalletDeleteRequest"
        description: Wallet Delete Request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Wallet successfully deleted
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
      summary: Delete wallet from persistent storage
      x-codegen-request-body-name: request
  /api/wallet/get:
    post:
      description: Gets a wallet from persistent storage and optional password and
        returns wallet details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api.WalletGetRequest"
        description: Wallet Restore Request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bursa.Wallet"
          description: Wallet successfully loaded
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
      summary: Get wallet from persistent storage
      x-codegen-request-body-name: request
  /api/wallet/list:
    get:
      description: List all wallets stored in secret storage matching our prefix
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: Ok
      summary: Lists wallets
  /api/wallet/restore:
    post:
      description: Restores a wallet using the provided mnemonic seed phrase and optional
        password and returns wallet details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api.WalletRestoreRequest"
        description: Wallet Restore Request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bursa.Wallet"
          description: Wallet successfully restored
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
      summary: Restore a wallet using a mnemonic seed phrase
      x-codegen-request-body-name: request
  /api/wallet/update:
    post:
      description: Updates a wallet from persistent storage and optional password
        and returns wallet details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api.WalletUpdateRequest"
        description: Wallet Update Request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Wallet successfully updated
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
      summary: Update a wallet in persistent storage
      x-codegen-request-body-name: request
components:
  schemas:
    api.WalletDeleteRequest:
      properties:
        name:
          maxLength: 100
          minLength: 1
          type: string
        password:
          type: string
      required:
      - name
      type: object
    api.WalletGetRequest:
      properties:
        name:
          maxLength: 100
          minLength: 1
          type: string
        password:
          type: string
      required:
      - name
      type: object
    api.WalletRestoreRequest:
      properties:
        account_id:
          maximum: 2147483647
          type: integer
        address_id:
          maximum: 2147483647
          type: integer
        committee_cold_id:
          maximum: 2147483647
          type: integer
        committee_hot_id:
          maximum: 2147483647
          type: integer
        drep_id:
          maximum: 2147483647
          type: integer
        mnemonic:
          minLength: 1
          type: string
        password:
          type: string
        payment_id:
          maximum: 2147483647
          type: integer
        stake_id:
          maximum: 2147483647
          type: integer
      required:
      - mnemonic
      type: object
    api.WalletUpdateRequest:
      properties:
        description:
          maxLength: 500
          type: string
        name:
          maxLength: 100
          minLength: 1
          type: string
        password:
          type: string
      required:
      - name
      type: object
    bursa.KeyFile:
      example:
        description: Payment Verification Key
        type: PaymentVerificationKeyShelley_ed25519
        cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
      properties:
        cborHex:
          example: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
          type: string
        description:
          example: Payment Verification Key
          type: string
        type:
          example: PaymentVerificationKeyShelley_ed25519
          type: string
      type: object
    bursa.Wallet:
      example:
        payment_vkey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        payment_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        committee_hot_extended_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        committee_hot_vkey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        stake_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        drep_vkey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        committee_cold_vkey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        payment_extended_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        drep_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        stake_address: stake1uy9ggsc9qls4pu9qvyyacwnmr9tt0gzcdt5s0zj4au8qkqc65ge8t
        committee_cold_extended_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        stake_vkey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        committee_cold_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        payment_address: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a429mg32v29q3cg4sdj5c9ts5vxknc0yutnj8x8r8qy2l2q9sgds2
        committee_hot_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        mnemonic: abandon abandon abandon abandon abandon abandon abandon abandon
          abandon abandon abandon about
        stake_extended_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
        drep_extended_skey:
          description: Payment Verification Key
          type: PaymentVerificationKeyShelley_ed25519
          cborHex: 5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880
      properties:
        committee_cold_extended_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        committee_cold_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        committee_cold_vkey:
          $ref: "#/components/schemas/bursa.KeyFile"
        committee_hot_extended_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        committee_hot_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        committee_hot_vkey:
          $ref: "#/components/schemas/bursa.KeyFile"
        drep_extended_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        drep_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        drep_vkey:
          $ref: "#/components/schemas/bursa.KeyFile"
        mnemonic:
          example: abandon abandon abandon abandon abandon abandon abandon abandon
            abandon abandon abandon about
          type: string
        payment_address:
          example: addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a429mg32v29q3cg4sdj5c9ts5vxknc0yutnj8x8r8qy2l2q9sgds2
          type: string
        payment_extended_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        payment_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        payment_vkey:
          $ref: "#/components/schemas/bursa.KeyFile"
        stake_address:
          example: stake1uy9ggsc9qls4pu9qvyyacwnmr9tt0gzcdt5s0zj4au8qkqc65ge8t
          type: string
        stake_extended_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        stake_skey:
          $ref: "#/components/schemas/bursa.KeyFile"
        stake_vkey:
          $ref: "#/components/schemas/bursa.KeyFile"
      type: object
x-original-swagger-version: "2.0"
