// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Blink Labs",
            "url": "https://blinklabs.io",
            "email": "support@blinklabs.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/wallet/create": {
            "get": {
                "description": "Create a wallet and return details",
                "produces": [
                    "application/json"
                ],
                "summary": "Create a wallet",
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/bursa.Wallet"
                        }
                    }
                }
            }
        },
        "/api/wallet/delete": {
            "post": {
                "description": "Deletes a wallet from persistent storage and optional password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete wallet from persistent storage",
                "parameters": [
                    {
                        "description": "Wallet Delete Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WalletDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/wallet/get": {
            "post": {
                "description": "Gets a wallet from persistent storage and optional password and returns wallet details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get wallet from persistent storage",
                "parameters": [
                    {
                        "description": "Wallet Restore Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WalletGetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet successfully loaded",
                        "schema": {
                            "$ref": "#/definitions/bursa.Wallet"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/wallet/list": {
            "get": {
                "description": "List all wallets stored in secret storage matching our prefix",
                "produces": [
                    "application/json"
                ],
                "summary": "Lists wallets",
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/wallet/restore": {
            "post": {
                "description": "Restores a wallet using the provided mnemonic seed phrase and optional password and returns wallet details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Restore a wallet using a mnemonic seed phrase",
                "parameters": [
                    {
                        "description": "Wallet Restore Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WalletRestoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet successfully restored",
                        "schema": {
                            "$ref": "#/definitions/bursa.Wallet"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/wallet/update": {
            "post": {
                "description": "Updates a wallet from persistent storage and optional password and returns wallet details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a wallet in persistent storage",
                "parameters": [
                    {
                        "description": "Wallet Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WalletUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.WalletDeleteRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.WalletGetRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.WalletRestoreRequest": {
            "type": "object",
            "required": [
                "mnemonic"
            ],
            "properties": {
                "account_id": {
                    "type": "integer",
                    "maximum": 2147483647
                },
                "address_id": {
                    "type": "integer",
                    "maximum": 2147483647
                },
                "committee_cold_id": {
                    "type": "integer",
                    "maximum": 2147483647
                },
                "committee_hot_id": {
                    "type": "integer",
                    "maximum": 2147483647
                },
                "drep_id": {
                    "type": "integer",
                    "maximum": 2147483647
                },
                "mnemonic": {
                    "type": "string",
                    "minLength": 1
                },
                "password": {
                    "type": "string"
                },
                "payment_id": {
                    "type": "integer",
                    "maximum": 2147483647
                },
                "stake_id": {
                    "type": "integer",
                    "maximum": 2147483647
                }
            }
        },
        "api.WalletUpdateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "bursa.KeyFile": {
            "type": "object",
            "properties": {
                "cborHex": {
                    "type": "string",
                    "example": "5820a9ebe2e435c03608fbdec443686d23661a796ab6d4dea71734c69b6dde310880"
                },
                "description": {
                    "type": "string",
                    "example": "Payment Verification Key"
                },
                "type": {
                    "type": "string",
                    "example": "PaymentVerificationKeyShelley_ed25519"
                }
            }
        },
        "bursa.Wallet": {
            "type": "object",
            "properties": {
                "committee_cold_extended_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "committee_cold_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "committee_cold_vkey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "committee_hot_extended_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "committee_hot_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "committee_hot_vkey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "drep_extended_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "drep_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "drep_vkey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "mnemonic": {
                    "type": "string",
                    "example": "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
                },
                "payment_address": {
                    "type": "string",
                    "example": "addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a429mg32v29q3cg4sdj5c9ts5vxknc0yutnj8x8r8qy2l2q9sgds2"
                },
                "payment_extended_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "payment_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "payment_vkey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "stake_address": {
                    "type": "string",
                    "example": "stake1uy9ggsc9qls4pu9qvyyacwnmr9tt0gzcdt5s0zj4au8qkqc65ge8t"
                },
                "stake_extended_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "stake_skey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                },
                "stake_vkey": {
                    "$ref": "#/definitions/bursa.KeyFile"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "bursa",
	Description:      "Programmable Cardano Wallet API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
